"""
环境变量标志注册表 + 严格校验（P0.5）。

解决的问题（历史教训）：
    V5_DAILY_TRADE_CAP_ENABLED 曾长期被禁用且未生效——根因是 env-flag 命名空间是开放的，
    拼错的 flag / 未登记的 flag 会"静默无效"，无任何告警。本模块为短线交易系统引入：
      1. KNOWN_FLAGS：所有代码实际识别的 env-flag 白名单（由静态扫描生成 + 人工维护）。
      2. validate_strict()：启动期扫描 os.environ，凡出现"以系统前缀开头但不在白名单"的 flag，
         视为疑似拼写/遗留/静默禁用，按策略 emit warning 或 fail。

设计原则：
    - 非侵入式：不改 settings.py 的 461 处读取逻辑，仅新增校验层。
    - 渐进收紧：默认 warn（记录可疑 flag），生产/CI 可设 ENV_STRICT=error 硬失败。
    - 安全相关 flag（白名单 SAFETY_CRITICAL_FLAGS）被设置为 falsy 时额外显式日志，防止"静默关闭风控"。

维护：
    - 新增 env-flag 时，必须同时登记到 KNOWN_FLAGS，否则启动告警。
    - 运行 `python -m backend.config.env_registry --scan` 可重新扫描代码生成候选清单。
"""
from __future__ import annotations

import logging
import os
import re
import sys

logger = logging.getLogger(__name__)

# [§63] `.env` 懒加载状态（CLI / 校验函数共用；只尝试一次）
_ENV_LOAD_ATTEMPTED = False
_ENV_LOADED_OK = False

# 系统使用的 env-flag 前缀。只有匹配这些前缀的才纳入校验（避免误报第三方库的 env）。
SYSTEM_PREFIXES: tuple[str, ...] = (
    "FACTOR_", "ML_", "QAA_", "RISK_", "EVENT_", "PROMOTION_", "RESOURCE_",
    "MAP_ELITES_", "PBO_", "EWC_", "DDGDA_", "DSPY_", "PROMPT_", "DERIBIT_",
    "MARKET_DATA_", "ADVERSARIAL_", "LLM_", "V5_", "AUTO_COIN_", "AGENT_",
    # [混合打分中心 ADR-23] 影子打分配置命名空间（mode/channel_b/interval 等，见 hybrid_scoring/config.py）
    "HYBRID_SCORE_",
    # [五Agent闭环 ADR-21] factors_lab 因子研究闭环配置命名空间（见 factors_lab/config.py）
    "FACTORS_LAB_",
    "AI_", "ANALYST_", "ASSISTANT_", "ARBITRAGE_", "REBATE_", "HYPERLIQUID_",
    "BINANCE_", "BYBIT_", "OKX_", "FULLAUTO_", "SCALP_", "MIDLONG_", "PAIR_",
    "WFO_", "BACKTEST_", "FEE_", "ENV_", "LIVE_", "PAPER_", "LONG_V2_", "LONG_TREND_",
    "MASTER_", "EXIT_", "FACTOR_", "PURGE_",
    # [§63 补齐] 此前遗漏的命名空间（未覆盖 ⇒ 这些前缀下的死键/拼错键**不会被校验发现**）
    "ANOMALY_", "ONCHAIN_", "HERMES_", "NSGA2_", "REENTRY_",
    "MARKET_SCANNER_", "TIER_", "KLINE_", "COLD_", "MM_",
    "MIDLONG_", "LOOP_", "SESSION_", "ACCOUNT_",
)

# 风控/安全关键 flag —— 被设为 falsy 时必须显式日志，禁止静默关闭。
SAFETY_CRITICAL_FLAGS: frozenset[str] = frozenset({
    "RISK_ENGINE_ENABLED",
    "RISK_MASTER_SWITCH_ENABLED",
    "V5_DAILY_TRADE_CAP_ENABLED",
    "PROMOTION_GATE_ENABLED",
    "RESOURCE_GUARD_ENABLED",
    "MARKET_DATA_VERIFIER_ENABLED",
    "LIVE_MODE_RISK_GUARDED",  # Live 模式风控主开关（README: 现硬失败）
    "SCALP_SHADOW_MODE",       # [v3 F1a] 关掉=短线恢复真单，只能经 edge_ledger 晋升门
    "RISK_ENGINE_V3_ENABLED",  # [v3 方向7] 关掉=RiskEngine 单入口只观察不拦截
    "RISK_DAILY_QUOTA_ENABLED",  # [v3 方向7] 关掉=日开仓配额不拦截
    "RISK_EVENT_WINDOWS_ENABLED",  # [v3 方向4] 关掉=下架/监控标签/清算级联 事件避险窗口不拦截
    "MIDLONG_PORTFOLIO_GATE_ENABLED",  # [§63 登记] 关掉=组合闸（净敞口/相关簇/并发）不拦截
    "MIDLONG_CHOP_GATE_ENABLED",  # [§63 登记] 关掉=震荡市入场闸不拦截
    "MIDLONG_FUNDING_GATE_ENABLED",  # [§63 登记] 关掉=资金费闸不拦截
    "MIDLONG_NO_PROGRESS_EXIT_ENABLED",  # [§63 登记] 关掉=无进展退出（软退出）不评估
    "MIDLONG_POSITION_MGMT_ENABLED",  # [§63 登记] 关掉=中线持仓管理段整体跳过
    "TIER_MID_ENABLED",  # [§63 登记] 关掉=中线车道整体停（含闸门）
    "TIER_LONG_ENABLED",  # [§63 登记] 关掉=长线车道整体停（含闸门）
    "LIVE_TPSL_SYNC",  # [§63 登记] 关掉=实盘 TPSL 不同步到交易所
    "FACTOR_HELDOUT_ENABLED",  # [§63 登记] 关掉=因子留出集验证不跑
    "FACTOR_SCORER_DSR_REQUIRED",  # [§63 登记] 关掉=因子评分不要求 DSR 门槛
    "FUNDING_SETTLE_ENABLED",  # [§63 登记] 关掉=资金费结算不执行
})

# 已登记的 env-flag 白名单。
# 初始来源：framework_rollout._AGGRESSIVE_DEFAULTS + 常用 settings flag。
# 运行 --scan 可补全。新增 flag 必须在此登记。
KNOWN_FLAGS: frozenset[str] = frozenset({
    "FACTOR_TRIALS_REGISTRY_PATH",  # [§63] trials_registry 的登记簿路径覆盖（生产读取）

    # ── [§63 批量登记 2026-09-10] 代码确实会读（字面/动态前缀/后缀拼接/settings）的 .env 键 ──
    # 保留在名单外的即是「.env 设了但代码任何方式都不读」的真·死键（注册表会精确报出）。
    "AI_CONCEPT_DRIFT_DETECTION_ENABLED",
    "AI_COUNTERFACTUAL_SANDBOX_ENABLED",
    "AI_CROSS_MARKET_TRANSFER_ENABLED",
    "AI_FACTOR_STRATEGY_FUSION_ENABLED",
    "AI_FACTOR_STRATEGY_JOINT_ENABLED",
    "AI_FREQUENCY_CONSTRAINT_CHAIN_ENABLED",
    "AI_MEMORY_DECAY_ENABLED",
    "AI_MULTI_ROUND_ANALYSIS_ENABLED",
    "AI_STRATEGY_DEEP_DIVE_ENHANCED_ENABLED",
    "AI_STRUCTURAL_MUTATION_ENABLED",
    "AI_TRADING_NARRATIVE_ENABLED",
    "AI_VPVR_V3_ENABLED",
    "AI_WALK_FORWARD_VALIDATION_ENABLED",
    "ASTERDEX_BACKFILL_MAX_REQ_PER_MIN",
    "ASTERDEX_MAX_REQ_PER_MIN",
    "ASTERDEX_RATE_BACKOFF_SEC",
    "ASTERDEX_STATS_INTERVAL_S",
    "ASTERDEX_TICKER_INTERVAL_S",
    "AUTH_LOCAL_TENANT",
    "AUTO_COIN_LONG_MAX_SLOTS",
    "AUTO_COIN_PARALLEL_SESSIONS",
    "AUTO_COIN_SOFT_FACTOR",
    "BACKEND_SERVE_WEB",
    "BINANCE_TICKER_INTERVAL_S",
    "BLOCKBEATS_API_KEY",
    "COINGLASS_API_KEY",
    "COINGLASS_FREE_API_KEY",
    "COIN_SELECT_ADMIN_TENANT_ID",
    "COIN_SELECT_AI_MAX_CANDIDATES",
    "COIN_SELECT_BOARD_TTL_HOURS",
    "COIN_SELECT_PLATFORM_ENABLED",
    # [2026-09-16 调研轮7] 平台选币看板调度器开关（默认跟随 AUTO_COIN_ENABLED；true=单独开启）
    "COIN_SELECT_PLATFORM_SCHEDULER_ENABLED",
    # [2026-09-16 调研轮8] 看板候选流动性下限（剔除 catalog 内几乎无法交易的标的；0=关闭）
    "COIN_SELECT_PLATFORM_MIN_LIQUIDITY",
    "COIN_SELECT_SCAN_INTERVAL_SEC",
    "COLD_EXCHANGE_MAX_REQ_PER_MIN",
    "COLD_EXCHANGE_MAX_REQ_PER_MIN_OKX",
    "COLD_EXCHANGE_RATE_BACKOFF_SEC",
    "COMMITTEE_CONTROL_ENABLED",
    "DATA_CENTER_MODE",
    "DB_LEAK_GUARD_KILL_SECONDS",
    "DRL_DEVICE",
    "EVOLUTION_MAX_WORKERS_CAP",
    "EXIT_CHANNEL_SHADOW_MAX_WR",
    "EXIT_CHANNEL_SHADOW_MIN_N",
    # [§78 执行 2026-09-11 / P19-B / P20] 统一出口熔断 + 重启重建（两者均可在 .env 回滚）
    "EXIT_CHANNEL_BREAKER_UNIFIED",
    "EXIT_CHANNEL_REBUILD_ON_LOAD",
    "FACTOR_CODEGEN_PREFER_CLOUD",
    "FACTOR_COMBO_MODE",
    "FACTOR_EVO_DECAY_TRIGGER",
    "FACTOR_EVO_DECAY_TRIGGER_ICIR",
    "FACTOR_EVO_GPU_CHUNK",
    "FACTOR_EVO_GPU_EVAL",
    "FACTOR_EVO_GPU_MAX_MEM_MB",
    "FACTOR_EVO_GPU_POP_BOOST",
    "FACTOR_EVO_QUICK_MAX_SEC",
    "FACTOR_EVO_SCALP_PERIODS",
    "FACTOR_EVO_SUBPROCESS",
    "FACTOR_GP_ALPS",
    "FACTOR_GP_ALPS_MAX_AGE",
    "FACTOR_GP_LAMBDA_HOF",
    "FACTOR_GP_LEXICASE_EPS",
    "FACTOR_GP_LLM_WARM_N",
    "FACTOR_GP_LLM_WARM_START",
    "FACTOR_GP_OBJECTIVE",
    "FACTOR_GP_SELECTION",
    "FACTOR_HELDOUT_RATIO",
    "FACTOR_IC_SHRINK_K",
    "FACTOR_IC_WEIGHT_MODE",
    "FACTOR_LIVE_ALLOWLIST_ONLY",
    "FACTOR_MCTS_MAX_WORKERS",
    "FACTOR_MIN_CAPACITY_USD",
    "FACTOR_NEUTRALIZE_BETA_TRAIN_RATIO",
    "FACTOR_OVERSIGHT_MAX_PBO",
    "FACTOR_SCORER_DSR_N_TRIALS",
    "FACTOR_SCORER_LAG1_MIN_RETENTION",
    "FACTOR_SCORER_MIDLONG_MIN_BARS_1D",
    "FACTOR_SCORER_MIDLONG_MIN_BARS_4H",
    "FACTOR_SCORER_NET_BUFFER",
    "FACTOR_SCORER_SCALP_MIN_BARS",
    "FACTOR_SLIMMING_POOL_MAX_CORR",
    "FACTOR_UNVERIFIED_WEIGHT",
    "FEATURE_FACTOR_EXPOSURE_ENABLED",
    "FEATURE_WFO_GATE_ENABLED",
    "FRED_API_KEY",
    "FUSION_MODE",
    "FUSION_PROBE_DAILY_QUOTA",
    "FUSION_PROBE_DAILY_QUOTA_LIVE",
    "FUSION_PROBE_DAILY_QUOTA_PAPER",
    "FUSION_PROBE_MIN_PWIN",
    "FUSION_PROBE_MIN_PWIN_PAPER",
    "FUSION_PROBE_MIN_SCORE",
    "FUSION_PROBE_SHORT_ENABLED",
    "FUSION_PROBE_SIZE_MULT",
    "FUSION_PWIN_ABSOLUTE_MIN",
    "FUSION_PWIN_EXPLORE_DAILY_QUOTA",
    "FUSION_PWIN_EXPLORE_DAILY_QUOTA_LIVE",
    "FUSION_PWIN_EXPLORE_DAILY_QUOTA_PAPER",
    "FUSION_PWIN_MISSING_MODE",
    "FUSION_PWIN_SAFETY_MULT",
    "FUSION_PWIN_TIERED",
    "FUSION_PWIN_TIERS",
    "FUSION_PWIN_UNUSABLE_MODE",
    "FUSION_PWIN_UNUSABLE_MODE_LIVE",
    "FUSION_PWIN_UNUSABLE_MODE_PAPER",
    "FUSION_RR_FLOOR",
    "FUSION_SCALP_PWIN_MIN",
    "FUSION_SCALP_PWIN_MIN_LIVE",
    "FUSION_SCALP_PWIN_STRONG",
    "FUSION_SHADOW_PROBE_MIN_PWIN",
    "FUSION_SHADOW_PROBE_MIN_SCORE",
    "FUSION_SHORT_PWIN_EXTRA",
    "GLM_ARBITER_MODEL",
    "HL_WHALE_ADDRESSES",
    "KLINE_BACKFILL_DAYS",
    "KLINE_BACKFILL_REQUEST_INTERVAL_SEC",
    "KLINE_DEPTH_BACKFILL_COLD_ENABLED",
    "KLINE_DEPTH_BACKFILL_COLD_LIMIT",
    "KLINE_DEPTH_BACKFILL_ENABLED",
    "KLINE_DEPTH_BACKFILL_IDLE_SEC",
    "KLINE_DEPTH_BACKFILL_ROUND_MAX_SEC",
    "KLINE_DEPTH_BACKFILL_SYMBOLS",
    "KLINE_DEPTH_BACKFILL_SYMBOL_LIMIT",
    "KLINE_MIN_1D_CANDLES",
    "KLINE_MIN_1H_CANDLES",
    "KLINE_P0_CONCURRENCY",
    "KLINE_P0_SYMBOL_CAP",
    "KLINE_P0_TIMEOUT_S",
    "KLINE_P0_ROUND_RETRY",   # [2026-09-11] P0 整轮全失败时同轮快速重试一次（默认 true）
    "KLINE_P1_ACTIVE_BATCH_SIZE",
    "KLINE_P1_ACTIVE_WEIGHT",
    "KLINE_P1_BATCH_SIZE",
    "KLINE_P1_COLD_WEIGHT",
    "KLINE_P1_CONCURRENCY",
    "KLINE_P1_DEPTH_DAYS_15M",
    "KLINE_P1_DEPTH_DAYS_1H",
    "KLINE_P1_DEPTH_DAYS_1M",
    "KLINE_P1_DEPTH_DAYS_30M",
    "KLINE_P1_DEPTH_DAYS_3M",
    "KLINE_P1_DEPTH_DAYS_5M",
    "KLINE_P1_INTERVAL_S",
    "KLINE_P1_TIMEOUT_S",
    "KLINE_P1_WATCH_INTERVAL_S",
    "KLINE_P1_WATCH_MAX_SYMBOLS",
    "KLINE_QUALITY_REPAIR_APPLY_ENABLED",
    "KLINE_QUALITY_REPAIR_ENABLED",
    "KLINE_QUALITY_REPAIR_EXCHANGES",
    "KLINE_QUALITY_REPAIR_PERIODS",
    "KLINE_QUALITY_REPAIR_SYMBOLS",
    "KLINE_REALTIME_SYMBOLS",
    "KLINE_REQUEST_INTERVAL_SEC",
    "KLINE_RETENTION_DAYS_15M",
    "KLINE_RETENTION_DAYS_1H",
    "KLINE_RETENTION_DAYS_1M",
    "KLINE_RETENTION_DAYS_30M",
    "KLINE_RETENTION_DAYS_3M",
    "KLINE_RETENTION_DAYS_4H",
    "KLINE_RETENTION_DAYS_5M",
    "KLINE_SYNC_EXCHANGES",
    "LIVE_BUDGET_MULT",
    "LIVE_CONF_EXTRA",
    "LIVE_DAILY_OPEN_CAP",
    "LIVE_KLINE_FORMING_REFRESH_S",
    "LIVE_LEARNING_HOOKS_ENABLED",
    "LIVE_PWIN_EXTRA",
    "LIVE_RECONCILE_AUTO_FIX",
    "LIVE_SCALP_DAILY_OPEN_CAP",
    "LIVE_SCALP_EV_META_HARD_FILTER",
    "LIVE_SCALP_EV_MIN_PCT_TIGHT",
    "LIVE_SCALP_META_MIN_PWIN",
    "LIVE_SCALP_V5_MIN_CONFIDENCE",
    "LIVE_SCALP_V5_MIN_RR",
    "LIVE_SCORE_EXTRA",
    "LIVE_V5_CONF_EXTRA",
    "LLM2_BUDGET_ENABLED",
    "LLM2_CAP_COMMITTEE",
    "LLM2_CAP_KLINE_ANALYSIS",
    "LLM2_CAP_MASTER",
    "LLM2_CAP_REVIEW",
    "LLM2_CAP_SCALP_CONFIRM",
    "LLM2_CAP_THESIS",
    "LLM2_DAILY_GLOBAL_CAP",
    "LONG_V2_SYNTH_TP_MULT",
    "MARKET_DATA_DC_ONLY",
    "MARK_PRICE_BINANCE_REFERENCE",
    "MIDLONG_AI_MIN_CONF_LONG",
    "MIDLONG_ATR_SL_MULT",
    "MIDLONG_ATR_FLOOR_MAX_LIFT",  # [2026-09-11] ATR 地板抬升上限（×原SL，默认 2.0；0=不设限）
    "MIDLONG_BRAIN_MAX_OUTPUT_TOKENS",
    "MIDLONG_BRAIN_OPEN_MARGIN_PCT",
    "MIDLONG_CHOP_ADX_MAX",
    "MIDLONG_CORR_CLUSTER_MAX",
    # [验收轮2 2026-09-14] 长车道（E1）专属簇帽（默认 3=BTC/ETH/SOL 同持；0=关闭）
    "MIDLONG_CORR_CLUSTER_MAX_LONG",
    "MIDLONG_FUNDING_ABS_WARN",
    "MIDLONG_FUNDING_HOLD_HOURS",
    # [2026-09-16 调研轮8] AI 中线候选流动性下限（看板 liquidity 分；0=关闭）
    "MIDLONG_AI_MIN_LIQUIDITY",
    # [2026-09-16 调研轮10] 中/长线 AI 候选口径：verdict 集合 + 新鲜度窗口（小时）
    "MIDLONG_AI_CANDIDATE_VERDICTS",
    "MIDLONG_AI_APPROVAL_WINDOW_H",
    # [2026-09-16 调研轮8] AI 中线候选总闸（false=中线只用固定币，等价 2026-09-04 旧行为）
    "MIDLONG_MID_AI_CANDIDATES_ENABLED",
    "MIDLONG_LONG_AI_CANDIDATES_ENABLED",
    # [2026-09-16 调研轮8] AI 中线候选每 tick 扫描配额（0=不扫 AI；默认 1）
    "MIDLONG_MID_AI_SCAN_SLOTS",
    "MIDLONG_MAX_NET_EXPOSURE_PCT",
    "MIDLONG_MAX_OPEN_POSITIONS",
    # [M3 2026-09-14] 长车道（E1 趋势 sleeve）独立并发帽（默认 8=TREND_MAX_POSITIONS；0=关闭）
    "MIDLONG_MAX_LONG_LANE_POSITIONS",
    # [P13 执行 2026-09-10] 每标的同向并发上限（0=关闭）
    "MIDLONG_MAX_SAME_SYMBOL_POSITIONS",
    # [调研轮7 2026-09-16] 硬止损距离上限（价格口径；0=关闭回滚）
    "MIDLONG_MAX_SL_PCT_MID",
    "MIDLONG_MAX_SL_PCT_LONG",
    # [P12 执行 2026-09-10] 组合闸名义口径开关（默认 true=与 PositionConstruction 同口径）
    "MIDLONG_PORTFOLIO_NOTIONAL_ALIGNED",
    "MIDLONG_MIN_NET_RR",
    "MIDLONG_NO_PROGRESS_HOURS_LONG",
    "MIDLONG_NO_PROGRESS_HOURS_MID",
    "MIDLONG_NO_PROGRESS_MIN_PEAK_R",
    "MIDLONG_POSITION_MGMT_INTERVAL_SEC",
    "MIDLONG_POSITION_MGMT_LLM_INTERVAL_SEC",
    "MIDLONG_POSITION_MGMT_PYRAMID_ONLY_PROFIT",
    "MIDLONG_REVIEW_LLM",
    "MIDLONG_RISK_PCT",
    # [调研轮18 2026-09-16] 单仓保证金占权益比例（可配；默认=原硬编码 3%/8%/15%）
    "MIDLONG_TIER_MARGIN_PCT_SHORT",
    "MIDLONG_TIER_MARGIN_PCT_MID",
    "MIDLONG_TIER_MARGIN_PCT_LONG",
    "MIDLONG_SWING_MIN_RR",
    "MIDLONG_SYMBOL_EXPOSURE_CAP_PCT",
    "ML_DEEP_MODEL_ENABLED",
    "ML_INFER_DEVICE",
    "ML_TRAIN_DEVICE",
    "ONCHAIN_ETHERSCAN_KEY",
    "PB_CHECK_TIMEOUT_S",
    # [P17-C① 执行 2026-09-10] 回撤判据的样本新鲜度阈值（≥该小时数无新样本 ⇒ 只告警不拒单）
    "PB_DD_STALE_HOURS",
    "PB_FREEZE_ENABLED",
    "PB_MAX_SYMBOL_EXPOSURE_PCT",
    "PB_MIDLONG_DRAWDOWN_SIGMA",
    "PB_MIDLONG_MAX_SYMBOL_EXPOSURE_PCT",
    "PB_PAPER_SKIP",
    "PB_REPAIR_SPAWN_EVO",
    "PB_SCALP_FREEZE_COOLDOWN_SEC",
    "PB_SCALP_MAX_SYMBOL_EXPOSURE_PCT",
    "PC_RISK_PER_TRADE_PCT_LONG",
    # [2026-09-10 D6 根因修复] 盈利回撤保护的武装门槛基准：true=原始名义（默认），
    # false=回滚旧的「3%×当前名义」口径（分批减仓后残仓会误触发全平）
    "PDG_BASIS_ORIGINAL_NOTIONAL",
    "PROMOTION_MAX_DRAWDOWN",
    "PROMOTION_MIN_DSR",
    "PROMOTION_MIN_TRADES",
    "PROMOTION_MIN_WIN_RATE",
    "REENTRY_LOSS_COOLDOWN_SEC_LONG",
    "REENTRY_LOSS_COOLDOWN_SEC_MID",
    "REENTRY_LOSS_COOLDOWN_SEC_SHORT",
    "REENTRY_SL_COOLDOWN_SEC_LONG",
    "REENTRY_SL_COOLDOWN_SEC_MID",
    "REENTRY_SL_COOLDOWN_SEC_SHORT",
    "REVIEW_MIN_INTERVAL_S",
    "REVIEW_OFFICER_ENABLED",
    "RISK_GATE_EXCEPTION_POLICY",
    "RISK_MAX_SUBMITS_PER_SEC",
    "RISK_P3_HARDFAT_SHADOW",
    "RISK_USE_MID_TIER_IMMUNE",
    "SCALP_DEFAULT_LEVERAGE",
    "SCALP_EV_MIN_PCT_PAPER",
    "SCALP_EXIT_FAST_CUT_MIN",
    "SCALP_EXIT_PARAM_OVERRIDE",
    "SCALP_EXIT_SL_PCT",
    "SCALP_EXIT_TP_PCT",
    "SCALP_LIQUIDITY_FILTER_ENABLED",
    "SCALP_LLM_CONFIRM_ENABLED",
    "SCALP_META_LOAD_WINDOW_DAYS",
    "SCALP_META_WICK_SAMPLE_WEIGHT",
    "SCALP_MIN_VOLUME_USD",
    "SCALP_MR_SIZE_MULTIPLIER",
    "SCALP_NEW_PARAM_MIN_SAMPLES",
    "SCALP_PWIN_FAIL_CLOSED",
    "SCALP_REDUCE_MIN_LOSS_PCT",
    "SCALP_ROI_T1",
    "SCALP_ROI_T2",
    "SCALP_ROI_T3",
    "SCALP_SHADOW_MODE_PAPER",
    "SCALP_SHORT_EARLY_MORNING_GATE",
    "SCALP_SHORT_EM_END_HOUR",
    "SCALP_SHORT_EM_EXTRA_MULT",
    "SCALP_SHORT_EM_MIN_RANGE_POS",
    "SCALP_SHORT_EM_START_HOUR",
    "SCALP_SHORT_PAPER_EXEMPT_MIN",
    "SCALP_SHORT_PAPER_FULL_MIN",
    "SCALP_USE_VETTED_FACTORS_ONLY",
    "SCHEDULER_MAX_WORKERS",
    "SMART_MONEY_ENABLED",
    "SMART_MONEY_EVENT_USD",
    "SMART_MONEY_MIN_NOTIONAL",
    "SMART_MONEY_OKX_TOP_N",
    "SNAPSHOT_PERIODS",
    "SNAPSHOT_SCHEDULER_ENABLED",
    "SNAPSHOT_SYMBOLS",
    "SYMBOL_RISK_BAN_HOURS",
    "THESIS_SHADOW_INCLUDE_LONG",
    "THESIS_SHADOW_MAX_PER_CYCLE",
    "THESIS_SHADOW_MAX_PER_DAY",
    "THESIS_SHADOW_MIN_INTERVAL_S",
    "WEEKLY_EVOLUTION_IN_PROCESS",
    # ── [§63 登记 2026-09-10] settings.py 已定义但此前未登记的 39 个键 ──
    # （这些键由 .env 读取、被 settings 解析；未登记时启动校验会把它们报成"疑似拼写/遗留"，
    #   而该告警此前因调用时机问题进不了文件日志——见报告 §63。）
    "AI_FACTOR_DISCOVERY_ENABLED",
    "AUTO_COIN_FORBID_LONG",
    "AUTO_COIN_SOURCE",
    "FACTOR_CLOUD_SYNC_ENABLED",
    "FACTOR_FUNDING_DIRECTION_FIX",
    "FACTOR_HELDOUT_ENABLED",
    "FACTOR_SCORER_DSR_REQUIRED",
    "FACTOR_SCORER_LAG1_ENABLED",
    "FACTOR_SCORER_LAG1_GATE",
    "FACTOR_SCORER_NEUTRALIZE",
    "FACTOR_SIGNAL_FILTER_NONDIRECTIONAL",
    "FUNDING_SETTLE_APPLY_PNL",
    "FUNDING_SETTLE_ENABLED",
    "FUSION_LOW_QUALITY_HOLD",
    "FUSION_REGIME_WEIGHT_MULTIPLIERS",
    "INTRADAY_LLM_ENABLED",
    "KLINE_P1_PERIOD_MODE",
    "LIVE_TPSL_SYNC",
    "LLM_BUDGET_PER_TENANT",
    "LLM_HTTPS_PROXY",
    "LLM_HTTP_PROXY",
    "MIDLONG_ATR_SIZING_ENABLED",
    "MIDLONG_CHOP_GATE_ENABLED",
    "MIDLONG_CORE_BASKET",
    "MIDLONG_CORR_CLUSTER_SYMBOLS",
    "MIDLONG_FUNDING_GATE_ENABLED",
    "MIDLONG_NO_PROGRESS_EXIT_ENABLED",
    "MIDLONG_PORTFOLIO_GATE_ENABLED",
    "MIDLONG_POSITION_MGMT_ENABLED",
    "MIDLONG_THESIS_CLOSE_CONFIRM_ENABLED",  # [2026-09-12 F39] 论题 should_close 反转确认闸
    # [调研轮18 2026-09-16] 失效价触发与条件原文语义对齐（原文"收盘跌破" vs 实现
    # "触碰即平"；逐笔回放 4/6 属条件未成立就被砍 ⇒ 少砍早单）
    "MIDLONG_THESIS_INV_REQUIRE_CLOSE",
    "MIDLONG_THESIS_INV_ESCAPE_DEPTH_PCT",
    "MIDLONG_THESIS_INV_CONFIRM_TF",
    # [调研轮19 2026-09-17] 回踩入场（同一批信号等小回撤再成交；超时市价兜底，非门禁）
    # [调研轮37/39 2026-09-17] 做空专项：模板族禁开空 + 空单规模乘子
    "MIDLONG_SHORT_BLOCK_TEMPLATE_SOURCES",
    "MIDLONG_SHORT_SIZE_MULT",
    # [调研轮40 2026-09-17] 模板族治理：退出 long 车道（tpl_long 21 笔均 −6.06）
    "MIDLONG_LONG_BLOCK_TEMPLATE_SOURCES",
    "MIDLONG_PULLBACK_ENTRY_ENABLED",
    "MIDLONG_PULLBACK_ENTRY_PCT",
    "MIDLONG_PULLBACK_ENTRY_TIMEOUT_S",
    "MIDLONG_CONTROLLED_DCA_ENABLED",  # [2026-09-12 F40] 受控逆势补仓（未反转行情替代小亏全平）
    "PAPER_FACTOR_LIVE_EXCLUDE",
    "RISK_V2_UNIFIED_STAGED_TP",
    "SCALP_DYNAMIC_HOLD_TPSL",
    "SCALP_EV_NEW_PARAM_EXPLORE",
    "SCALP_MARKET_AWARE_TPSL",
    "SCALP_RESEARCH_ENABLED",
    "SCALP_SHORT_LIVE_STRICT",
    "SCALP_SHORT_REQUIRES_TREND_DOWN",
    "TIER_LONG_ENABLED",
    "TIER_MID_ENABLED",
    # ── auto-merged from codebase scan + manual entries ──
    "ACTIVE_MARKET_FLOW_EXCHANGES",
    "ADVERSARIAL_DEBATE_ENABLED",
    "AGENT_FACT_GUARD_MODE",
    "AGENT_FACT_GUARD_PAPER_ENFORCE",
    "AI_AB_FRAMEWORK_ENABLED",
    "AI_GOVERNED_COMPARE_DAYS",
    "AI_GOVERNED_COMPARE_MIN_SAMPLES",
    "AI_GOVERNED_PF_DROP",
    "AI_GOVERNED_WEIGHT_CONFIRMED",
    "AI_GOVERNED_WIN_RATE_GAP",
    "AI_CAUSAL_DISCOVERY_ENABLED",
    "AI_EVOLUTION_LEVEL",
    "AI_EXTEND_HOLD_HOURS_MAX",
    "AI_EXTEND_HOLD_HOURS_MIN",
    "ALERT_WEBHOOK_URL",
    "ALERT_P0_ENABLED",
    "ALL_PROXY",
    "ALPHA_DATA_DIR",
    "ANALYST_RULES_MAX_PARALLEL",
    "ANALYST_RULES_PARALLEL",
    "ANALYTICS_DATABASE_URL",
    "APPDATA",
    "ARBITRAGE_PAPER_AUTO_EXECUTE",
    "ARBITRAGE_PAPER_TICK_SECONDS",
    # [轮94 P2-14] 套利中心总开关。`arbitrage_routes.py:61` 与
    # `rebate_arb/arb_switches.py:117` 都在读它（默认 false = 中心已停），
    # 但此前**从未登记** —— 于是启动校验把它报成"疑似拼写/遗留"，
    # 而 `test_env_registry_visibility_20260910::test_registry_unknowns_are_exactly_the_dead_keys`
    # 又要求注册表报出的键必须同时是静态审计认定的死键，两边对不上 ⇒ 该测试长期失败。
    "ARBITRAGE_CENTER_ENABLED",
    "ARB_V3_MAX_EXECUTIONS_PER_TICK",
    "ARCHIVED_CLEANUP_DAYS",
    "ASSISTANT_DAILY_REPORT_HOUR_UTC",
    "AUDIT_HMAC_KEY",
    # [P10 执行 2026-09-10] 保留期/轮转类键（原先既不在白名单、也不在任何 SYSTEM_PREFIX 下
    # ⇒ 注册表校验完全看不到它们；这里显式登记，便于后续把 AUDIT_/LOG_ 前缀纳入校验）
    "AUDIT_JSONL_MAX_BYTES",
    # [§64 执行 2026-09-10] 启动器（scripts/_restart_backend_clean.py）的 console 日志轮转阈值
    "BACKEND_CONSOLE_LOG_MAX_MB",
    "AUDIT_BACKUP_KEEP_DAYS",
    "LOG_RETENTION_DAYS",
    "REPORT_RETENTION_DAYS",
    "AI_DECISION_LOG_RETENTION_DAYS",
    "AUTO_COIN_AI_REVIEW_INTERVAL_SEC",
    "AUTO_COIN_AI_REVIEW_MAX_CANDIDATES",
    "AUTO_COIN_BLACKLIST_DAYS",
    "AUTO_COIN_BLACKLIST_SCORE",
    "AUTO_COIN_BOARD_VOLUME_PROBE_MIN",
    "AUTO_COIN_BOARD_VOLUME_SOFT",
    "AUTO_COIN_CANDIDATE_TOP_N",
    "AUTO_COIN_COOLING_HOURS",
    "AUTO_COIN_COOLING_LONG_HOURS",
    "AUTO_COIN_COOLING_SHORT_HOURS",
    "AUTO_COIN_COOLING_VERY_LONG_HOURS",
    "AUTO_COIN_DEFAULT_EXCHANGE",
    "AUTO_COIN_DIVERSITY_WEIGHT",
    "AUTO_COIN_ENABLED",
    "AUTO_COIN_EVALUATION_INTERVAL",
    "AUTO_COIN_EVENT_DEDUP_SEC",
    "AUTO_COIN_EXPIRY_KEEP_SCORE",
    "AUTO_COIN_EXPIRY_REMOVE_SCORE",
    "AUTO_COIN_FACTOR_BLEND",
    "AUTO_COIN_FACTOR_MATCH_ENABLED",
    "AUTO_COIN_FACTOR_MIN_ABS_ALPHA",
    "AUTO_COIN_FACTOR_MIN_MARKET",
    "AUTO_COIN_FAST_AI_MAX_PER_HOUR",
    "AUTO_COIN_FAST_FORCE_AI",
    "AUTO_COIN_FAST_INTERVAL_SEC",
    "AUTO_COIN_FAST_MIN_GAP_SEC",
    "AUTO_COIN_FLOW_OI_CLIP_PCT",
    "AUTO_COIN_GRACE_CYCLES",
    "AUTO_COIN_MARKET_WEIGHT",
    "AUTO_COIN_MAX_COUNT",
    "AUTO_COIN_MAX_HOLD_HOURS",
    "AUTO_COIN_MAX_PER_SECTOR",
    "AUTO_COIN_MIN_AI_CONFIDENCE",
    "AUTO_COIN_MIN_HOLD_HOURS",
    "AUTO_COIN_MIN_SCORE",
    "AUTO_COIN_MULTI_LANE_ENABLED",
    "PAPER_AUTO_COIN_MULTI_LANE",
    "COIN_RANK_ENGINE_ENABLED",
    "COIN_RANK_GATES_ENABLED",
    "COIN_RANK_FEEDBACK_ENABLED",
    "COIN_RANK_TRAP_SOFT_REJECT",
    "COIN_RANK_TRAP_HARD_REJECT",
    "COIN_RANK_MTF_MIN_STRONG",
    "COIN_RANK_FEEDBACK_INTERVAL_SEC",
    # [2026-09-12 RTGNN 迁移] 图信号试点（零训练 lead/dm）+ RTGNN-lite 影子模型
    "COIN_RANK_GRAPH_SIGNAL_ENABLED",
    "COIN_RANK_GRAPH_WEIGHT",
    "COIN_RANK_GRAPH_LEAD_WEIGHT",
    "COIN_RANK_GRAPH_LEAD_PERIOD",
    "COIN_RANK_GRAPH_MOM_PERIOD",
    "COIN_RANK_GRAPH_LEAD_COUNT",
    "COIN_RANK_GRAPH_MOM_COUNT",
    "COIN_RANK_GRAPH_MAX_LAG",
    "COIN_RANK_GRAPH_ANCHORS",
    "COIN_RANK_GRAPH_TTL_SEC",
    "COIN_RANK_GRAPH_MIN_BARS",
    "GRAPH_RANK_ENABLED",
    "GRAPH_RANK_PERIOD",
    "GRAPH_RANK_COUNT",
    "GRAPH_RANK_LOOKBACK",
    "GRAPH_RANK_HORIZON",
    "GRAPH_RANK_EPOCHS",
    "GRAPH_RANK_BATCH_SIZE",
    "GRAPH_RANK_LR",
    "GRAPH_RANK_PATIENCE",
    "GRAPH_RANK_LAMBDA_RANK",
    "GRAPH_RANK_MODEL_PATH",
    "GRAPH_RANK_SCORE_TTL_SEC",
    "GRAPH_RANK_MIN_ASSETS",
    "GRAPH_RANK_DEVICE",
    "AUTO_COIN_GRAPH_SCORE_ENABLED",
    "AUTO_COIN_W_GRAPH",
    "UNIVERSE_DEDUP_DIRECTIONAL",
    "UNIVERSE_MAX_LEAD_REDUNDANT",
    "AUTO_COIN_NEWS_COOLING_HOURS",
    "AUTO_COIN_NEWS_HALF_LIFE_MIN",
    "AUTO_COIN_NEWS_HOURS",
    "AUTO_COIN_NEWS_MIN_CONF",
    "AUTO_COIN_NORMAL_INTERVAL_SEC",
    "AUTO_COIN_PERFORMANCE_THRESHOLD",
    "AUTO_COIN_PERF_WEIGHT",
    "AUTO_COIN_POSITION_SIZE_MULT",
    "AUTO_COIN_PROBE_MIN_CLOSED",
    "AUTO_COIN_PROBE_SIZE_MULT",
    "AUTO_COIN_REPLACEMENT_MARGIN",
    "AUTO_COIN_RETENTION_WEIGHT",
    "AUTO_COIN_SCAN_INTERVAL",
    "AUTO_COIN_MID_RESAMPLE_SEC",
    "AUTO_COIN_MID_MAX_SLOTS",
    "MIDLONG_AI_MIN_CONF",
    # [2026-09-09 根因修复] LLM 方向需框架同意（见 decision_hub._llm_direction_requires_framework_agree）
    "MLTO_LLM_DIRECTION_REQUIRE_FW_AGREE",
    # [M8 2026-09-14] OWM 权重读端接回主脑 conviction（默认 true；false=回滚 write-only）
    "MLTO_OWM_INTO_BRAIN",
    # [2026-09-09] 因子打分成本口径：empirical=真实费率+实测滑点
    "FACTOR_SCORER_COST_SOURCE",
    "FACTOR_SCORER_COST_EXCHANGE",
    # [2026-09-09 根因修复] 位置闸 + 中线出场参数标定（见 .env 同名注释块）
    "MIDLONG_LOCATION_GATE_ENABLED",
    # [M4 2026-09-14] paper 下位置闸从 veto 降级为缩仓放行（默认 true；false=旧 veto）
    "MIDLONG_LOCATION_PAPER_SHRINK_ENABLED",
    # [M4 2026-09-14] paper 位置闸缩仓倍数（0.25）
    "MIDLONG_LOCATION_PAPER_SHRINK_MULT",
    # [2026-09-16 调研轮7] 追高天花板（24h 区间分位 ≥ 该值 → paper 也硬否决；0=关闭）
    "MIDLONG_LOCATION_PAPER_SHRINK_CEILING",
    # [§78 补登记 2026-09-11] 位置闸"延后到长线闸"开关（交叉验证工具发现：有读取方但未登记）
    "MIDLONG_LOCATION_DEFER_TO_LONG_GATE",
    "MIDLONG_CHOP_MODE",
    "MIDLONG_DOWN_SHORT_MODE",
    # [M4 2026-09-14] learned 窄带闸 paper 探针（默认 true=缩仓放行；false=旧 hold）
    "MIDLONG_LEARNED_PAPER_PROBE",
    # [M4 2026-09-14] learned 窄带 paper 探针缩仓倍数（默认 0.25）
    "MIDLONG_LEARNED_PAPER_PROBE_MULT",
    # [2026-09-11 V11 深度解析] trend_broken 价格闸：浮亏 < 该%（价格口径，默认 3.0
    # = SL6% 的一半）且日线非 down → 不执行方向复查平仓（交给 SL/追踪）；0=关闭回滚
    "MIDLONG_TREND_BROKEN_MIN_PRICE_LOSS",
    # [2026-09-09 第十五轮] learned 空头准入第三条件：chg24 上限（防追涨摸顶）
    "MIDLONG_SHORT_CHG24_MAX_PCT",
    # [2026-09-11 用户指令] 模拟账户不做亏损类冻结：账户模式解析兜底 + paper 跳过闸
    # （唯一权威见 backend/services/risk_management/loss_lock_policy.py）
    "DEFAULT_TRADING_MODE",
    # 注：`PB_PAPER_SKIP` 已在上面登记过（重复键会破坏"键唯一"契约测试，此处不再重复）
    # [2026-09-09 第十六轮] 多头独立治理：learned（默认）/ regime_only / allow_all
    # [2026-09-09 第十七/十八轮] up 分支 chg24∈[3,6)（spike 上界）；
    #   chop 分支 pos≥60% 且 chg24≥2%（第十八轮按近 30 天实际 P&L 回滚）
    "MIDLONG_LONG_MODE",
    "MIDLONG_LONG_CHG24_MIN_UP_PCT",
    "MIDLONG_LONG_CHG24_MAX_UP_PCT",
    "MIDLONG_LONG_CHG24_MIN_CHOP_PCT",
    "MIDLONG_LONG_CHOP_POS_MIN_PCT",
    # [2026-09-10 第二十一轮] learned 特征闸作用车道（默认 mid；long 层被误伤 +$55）
    "MIDLONG_LONG_LEARNED_TIERS",
    "MM_W_BASE_BP",
    "MM_K_INV",
    "MM_MAX_ONE_SIDE_SEC",
    "MM_STOP_LOSS_BP",
    # [§82 执行 2026-09-11 / 决策 P5-A] 车道级风控闸门开关（默认 false：
    # toxic_streak / 日亏闸在接线前**从未生效**，打开后影子证据基线变保守）
    "MM_LANE_LIMITS_ENFORCE",
    # [2026-09-16 调研轮7] MM 车道自进化开关/纪元（.env 已存在但未登记 → 死键审计交叉验证失败）
    "MM_AUTO_EVOLVE",
    "MM_EVOLUTION_SINCE",
    # [2026-09-16 调研轮8] MM 车道 ticker（.env 已存在但未登记 → 死键审计交叉验证失败）
    "MM_LANE_TICKER",
    # [§84 执行 2026-09-11 / 决策 P27-A / 缺陷 #69] 熔断证据新鲜度（天；0=关闭约束）
    "BREAKER_EVIDENCE_STALE_DAYS",
    # [§88 执行 2026-09-11 / 决策 P29-A] long 层 SL 距离上限（0=关闭）
    "MIDLONG_SL_MAX_PCT_LONG",
    # [调研轮15b 2026-09-16] mid 层同键 + 全局回退键：mid 层此前**只有**另一种拼写
    # MIDLONG_MAX_SL_PCT_MID ⇒ 引擎收口层 cap=0，上限静默失效（实测 mid SL 距离
    # 4.67% = nature 硬下限 4.5%）。两者都登记，消除"配置了却不生效"的死键盲区。
    "MIDLONG_SL_MAX_PCT_MID",
    "MIDLONG_SL_MAX_PCT",
    # [调研轮16 2026-09-16] AI 候选策略按需供给（开关 / 每日上限 / 实盘许可）
    "MIDLONG_AI_AUTOCREATE_STRATEGY",
    "MIDLONG_AI_AUTOCREATE_MAX_PER_DAY",
    "MIDLONG_AI_AUTOCREATE_LIVE",
    # [调研轮17 2026-09-16] 模板策略复用守卫（该层已有 active 时不再新建，抑制
    # "新建→被去重归档"的 churn，避免归档时刻清空某层 active）
    "HEALTH_TEMPLATE_REUSE_GUARD",
    # [§95 2026-09-11 / 目标③] 抑制上限（0=关闭）+ 计数窗口小时（默认 24）
    "EXIT_SUPPRESS_MAX_COUNT",
    "EXIT_SUPPRESS_WINDOW_H",
    "MIDLONG_LOCATION_MAX_PCT_LONG",
    "MIDLONG_LOCATION_MIN_PCT_SHORT",
    "MIDLONG_LOCATION_MAX_ADVERSE_24H_PCT",
    "MIDLONG_LOCATION_REGIMES",
    "MIDLONG_LOCATION_TIERS",
    "EXIT_POLICY_MID_SL_PCT",
    "EXIT_POLICY_MID_TIME_LIMIT_SEC",
    "EXIT_POLICY_MID_MIN_ROI",
    # [2026-09-10 第十九轮] 浮盈锁：mid 追踪激活 3.0→0.5%、回撤 1.5→0.15%；
    # SL 改善步长防抖（价格 %）
    "EXIT_POLICY_MID_TRAILING_ACTIVATION_PCT",
    "EXIT_POLICY_MID_TRAILING_CALLBACK_PCT",
    "EXIT_POLICY_TRAILING_MIN_STEP_PCT",
    "AUTO_COIN_MAX_HOLD_HOURS_MID",
    "AUTO_COIN_SCORE_V3_ENABLED",
    "AUTO_COIN_SECTOR_LEADER_RET_1H",
    "AUTO_COIN_SECTOR_LEADER_VOL_Z",
    "AUTO_COIN_SECTOR_PEER_TOP_K",
    "AUTO_COIN_SECTOR_SIGNAL_ENABLED",
    "AUTO_COIN_V5_CONF_PENALTY",
    "AUTO_COIN_V5_CONF_RELIEF",
    "AUTO_COIN_V5_MIN_RR",
    "AUTO_COIN_W_BASE",
    "AUTO_COIN_W_FLOW",
    "AUTO_COIN_W_NEWS",
    "AUTO_COIN_W_SECTOR",
    "AUTO_COIN_W_WHALE",
    "AUTO_COIN_IC_WEIGHTS_ENABLED",
    "AUTO_COIN_IC_MIN_SAMPLES",
    "AUTO_COIN_IC_CACHE_TTL_SEC",
    "AUTO_COIN_IC_LOOKBACK_DAYS",
    "AUTO_COIN_CORR_DEDUP_THRESHOLD",
    "AUTO_COIN_LLM_COMPOSE_ENABLED",
    "AUTO_COIN_LLM_COMPOSE_MAX",
    "WISDOM_QUALITY_PNL_PCT_GATE",
    "WISDOM_QUALITY_PNL_USD_GATE",
    "WISDOM_AMOUNT_SCALE_USD",
    "WISDOM_MIN_QUALITY_SAMPLES",
    "PARAM_DOMAIN_EXPAND_ENABLED",
    "PARAM_DOMAIN_EXPAND_RATIO",
    "PARAM_DOMAIN_EXPAND_MAX",
    "PARAM_DOMAIN_MIN_SAMPLES",
    "PARAM_DOMAIN_MIN_CONFIDENCE",
    "PARAM_DOMAIN_CACHE_TTL_SEC",
    "QAA_SCHEDULER_ENABLED",
    "QAA_REBATE_SCHEDULE_ENABLED",
    "QAA_REBATE_INTERVAL_SEC",
    "QAA_FULLAUTO_SCHEDULE_ENABLED",
    "QAA_FULLAUTO_INTERVAL_SEC",
    "AUTO_COIN_WATCH_TTL_MIN",
    "AUTO_COIN_WHALE_DIR_THRESHOLD",
    "BACKEND_API_KEY",
    "BACKEND_HOST",
    "BACKEND_LOG_LEVEL",
    "BACKEND_PORT",
    "BACKTEST_FILL_MODEL",
    "BACKTEST_INTRABAR_RESOLUTION",
    "BACKTEST_SLIPPAGE_UNIFIED",
    "BINANCE_HTTPS_PROXY",
    "BINANCE_HTTP_PROXY",
    "BLOCK_FALLBACK_OPENS",
    "CMAES_TRIALS",
    "CNY_USD_RATE",
    "COINALYZE_API_KEY",
    "CONSECUTIVE_LOSS_PROTECTION_ENABLED",
    "COORDINATOR_CONSUME_SNAPSHOT_KLINES",
    "COORDINATOR_SNAPSHOT_MAX_AGE_SEC",
    "CROSS_TIER_CONFLICT_POLICY",
    "CRYPTOPANIC_API_KEY",
    "CRYPTO_ALPHA_ENABLED",
    "CVD_AGGREGATION_WINDOW_SECONDS",
    "CYCLE_PROB_GATE_ENABLED",
    "CYCLE_PROB_GATE_MARGIN",
    "CYCLE_PROB_GATE_MIN_CALIBRATION",
    "CYCLE_PROB_GATE_PAPER_SIZE_MULT",
    "DATABASE_URL",
    "DB_CONNECT_TIMEOUT",
    "DB_LEAK_GUARD_AGE_SECONDS",
    "DB_MAX_OVERFLOW",
    "DB_POOL_MAX_OVERFLOW",
    "DB_IDLE_IN_TXN_TIMEOUT_MS",
    "DB_POOL_RECYCLE",
    "DB_POOL_SIZE",
    "DB_POOL_TIMEOUT",
    "DDGDA_ENABLED",
    "DDGDA_MAX_HALFLIFE",
    "DDGDA_MIN_HALFLIFE",
    "DDGDA_MODE",
    "DECISION_PRICE_GATE_ENABLED",
    "DECISION_PRICE_MAX_DEVIATION_PCT_LIVE",
    "DECISION_PRICE_MAX_DEVIATION_PCT_PAPER",
    "DEEPSEEK_API_KEY",
    "DEEPSEEK_BASE_URL",
    "DEEPSEEK_THINKING_MODE",
    "DEEPSEEK_REASONING_EFFORT",
    "DEEPSEEK_THINKING_MAX_TOKENS_FLOOR",
    "DEFAULT_EXCHANGE",
    "DEFAULT_TRADE_NATURE_FOR_MISSING",
    "DEFENSIVE_TIERED_MODE",
    "DERIBIT_OPTIONS_ENABLED",
    "DEV_MODE",
    "DINGTALK_DEFAULT_MAX_PER_HOUR",
    "DINGTALK_DEFAULT_SIGN_SECRET",
    "DINGTALK_DEFAULT_WEBHOOK",
    "DINGTALK_ENABLED",
    "DINGTALK_MAX_RETRY_COUNT",
    "DINGTALK_QUEUE_SIZE",
    "DINGTALK_REQUEST_TIMEOUT",
    "DINGTALK_RETRY_DELAY",
    "DINGTALK_WORKER_COUNT",
    "DIRECTION_COHERENCE_MODE",
    "DIRECTION_LLM_MAX_TOKENS",
    "DRL_RETRAIN_AUTO",
    "DRL_SHADOW_MODE",
    "DSPY_COMPILE_ENABLED",
    "DSPY_MAX_TRIALS",
    "DSPY_RECOMPILE_INTERVAL_DAYS",
    "DUAL_AGENT_MODE",
    "DYNAMIC_LEVERAGE_ENABLED",
    "DYNAMIC_LEVERAGE_MAX",
    "DYNAMIC_LEVERAGE_MIN",
    "DYNAMIC_THRESHOLD_ENABLED",
    "DYNLEV_DRAWDOWN_WEIGHT",
    "DYNLEV_EQUITY_REF",
    "DYNLEV_FUNDING_WEIGHT",
    "DYNLEV_REGIME_WEIGHT",
    "DYNLEV_VOL_WEIGHT",
    "ENABLE_COORDINATOR",
    "ENABLE_DRL_INTEGRATION",
    "ENABLE_KELLY_POSITION",
    "ENABLE_ORCHESTRATOR_OVERRIDE",
    "ENABLE_PORTFOLIO_RISK",
    "ENABLE_REDUCE_COOLDOWN",
    "ENABLE_RL_POSITION_SIZER",
    "ENVIRONMENT",
    "ENV_STRICT",
    # [轮94 P2-14] 启动期可选输出「环境变量治理体检」计数（默认关闭；扫全仓约 1.2s）。
    # 打开后 `validate_strict()` 会多打一行 info，并在治理债超基线时打 warning。
    "ENV_GOVERNANCE_REPORT",
    "ETHERSCAN_API_KEY",
    "EVENT_SOURCING_ENABLED",
    "EVENT_SOURCING_LOG_PATH",
    "EVENT_SOURCING_PHASE2_READ",
    "EVENT_SOURCING_PHASE2_RECONCILE",
    "EVENT_SOURCING_PHASE3",
    "EVENT_SOURCING_WRITE_RETIRE_DB",
    "EWC_ENABLED",
    "EWC_LAMBDA",
    "FACTOR_ACTIVE_CAP",
    "FEATURE_FACTOR_LABELS_ENABLED",
    "FACTOR_EVO_TEST_DAYS",
    "FACTOR_EVO_TRAIN_DAYS",
    "FACTOR_EVO_VAL_DAYS",
    "FACTOR_EVO_BUDGET_MAX_SEC",
    "FACTOR_MCTS_ENABLED",
    "FACTOR_MIN_NET_IC",
    "FACTOR_CATEGORY_DEDUP_ENABLED",
    "FACTOR_CATEGORY_MAX_SHARE",
    "FACTOR_MERGE_REGISTRY",
    "FACTOR_MINER_MAX_ATTEMPTS",
    "FACTOR_SCORER_COST",
    "FACTOR_SCORER_FWD_PERIOD",
    "FACTOR_SCORER_INTERVAL",
    "FACTOR_SCORER_LOOKBACK_BARS",
    "FACTOR_SCORER_MIDLONG_FWD_1D",
    "FACTOR_SCORER_MIDLONG_FWD_4H",
    "FACTOR_SCORER_MIDLONG_LOOKBACK",
    "FACTOR_SCORER_MIDLONG_LOOKBACK_1D",
    "FACTOR_SCORER_MIDLONG_MIN_SHARPE",
    "FACTOR_SCORER_MIN_NET_RETURN",
    "FACTOR_SCORER_MIN_SHARPE",
    "FACTOR_SCORER_REDUNDANCY_CORR",
    "FACTOR_SCORER_SYMBOLS",
    "FACTOR_WEIGHTING_MODE",
    "FEISHU_ASSISTANT_ENABLED",
    "FEISHU_ENCRYPT_KEY",
    "FEISHU_VERIFICATION_TOKEN",
    "FRONTEND_AUTO_BUILD",
    "FRONTEND_ORIGIN",
    "FULLAUTO_AI_DOMINANT",
    "FULLAUTO_AI_UNIFIED_ANALYSIS",
    "FULLAUTO_ANALYST_FALLBACK",
    "FULLAUTO_CAPTURE_UNIFIED_SNAPSHOT",
    "FULLAUTO_FAST_DECISION_MODE",
    "FULLAUTO_FLOW_MODE",
    "FULLAUTO_LEARNING_INTEGRATION_EVERY_N",
    "FULLAUTO_MAINTENANCE_EVERY_N_TICKS",
    "FULLAUTO_MAX_STRATEGIES_PER_TICK",
    "FULLAUTO_MAX_SYMBOLS_PER_TICK",
    "FULLAUTO_ORCH_SKIP_SYNC_WHEN_CACHE_FRESH",
    "FULLAUTO_RUN_TRADING_ORCHESTRATOR",
    "FULLAUTO_SNAPSHOT_TIMEOUT_S",
    "FULLAUTO_TRADING_ORCHESTRATOR_TIMEOUT_S",
    "FUNDING_ARB_ENABLED",
    "FUNDING_SETTLE_INTERVAL_SEC",
    "HERMES_AB_TRAFFIC_RATIO",
    "HERMES_GENESIS_MAX_ACTIVE_INCUBATIONS",
    "HERMES_L2_AB_ENABLED",
    "HERMES_L3_AUTO_ACCEPT_BATCH",
    "HERMES_L3_AUTO_ACCEPT_PAPER",
    "HF_HOME",
    "HOLD_TIMEOUT_EXPIRED_REVIEW_SEC",
    "HOLD_TIMEOUT_NEAR_REVIEW_SEC",
    "HOLD_TIME_TUNING_LOCKED",
    "HTTPS_PROXY",
    "HTTP_PROXY",
    "HYBRID_LEARNED_BLEND",
    "HYBRID_SIGNAL_MODE",
    "HYPERLIQUID_API_URL",
    "HYPERLIQUID_BUILDER_ADDRESS",
    "HYPERLIQUID_BUILDER_FEE",
    "HYPERLIQUID_ENCRYPTION_KEY",
    "HYPOTHESIS_AUTO_EVOLVE",
    "KELLY_AS_UPPER_BOUND",
    "KLINE_AGG_EXCHANGES",
    "KLINE_AGG_BASELINE_FALLBACK_ENABLED",  # [2026-09-11] 基准所过期→新鲜所单所回退（默认 true）
    "KLINE_VOLUME_AGGREGATION_ENABLED",
    "KLINE_ANALYST_MAX_PARALLEL",
    "KLINE_ANALYST_MODE",
    "KLINE_CHANGE_THRESHOLD_PCT",
    "KLINE_COLLECTION_TIMEOUT_S",
    "KLINE_COLLECTOR_MAX_WORKERS",
    "KLINE_FORCE_REFRESH_EVERY_N_TICKS",
    "KLINE_FRESHNESS_INTERVAL_S",
    "KLINE_FRESHNESS_PERIODS",
    "KLINE_FRESHNESS_SYMBOLS",
    "KLINE_LLM_CACHE_MAX_SIZE",
    "KLINE_LLM_CACHE_TTL",
    "KLINE_LLM_MAX_PER_CYCLE",
    "KLINE_QUALITY_REPAIR_EXCHANGE",
    "KLINE_QUALITY_REPAIR_FETCH_TIMEOUT",
    "KLINE_QUALITY_REPAIR_INTERVAL",
    "KLINE_QUALITY_REPAIR_LIMIT",
    "KLINE_QUALITY_REPAIR_SETTLE_PERIODS",
    "KLINE_QUALITY_REPAIR_SETTLE_SECONDS",
    "KLINE_QUALITY_REPAIR_VOLUME_TOLERANCE",
    "KLINE_ROTATE_BATCH_SIZE",
    "KLINE_USE_LOCAL_LLM",
    "LAYER_BUDGET_SCALP",
    "LAYER_BUDGET_SWING",
    "LAYER_BUDGET_TREND",
    "LEARNED_WEIGHTING_ENABLED",
    "LEARNING_CORE_ENABLED",
    "LEARNING_LEDGER_ENABLED",
    "LEARNING_LOOP_COORD_INTERVAL_S",
    "LEARNING_LOOP_ENABLED",
    "LEARNING_LOOP_KELLY_INTERVAL_S",
    "LEARNING_LOOP_OUTCOME_INTERVAL_S",
    "LEARNING_LOOP_PAPER_BACKFILL_INTERVAL_S",
    "LEGACY_RISK_HARD_ROLLBACK",
    "LIVE_CONSTITUTIONAL_RISK_ENABLED",
    "LIVE_DIRECTION_COHERENCE_MODE",
    "LIVE_MODE",
    # [轮98 · P1-8 路由结论] 实盘子仓位账本开关：决定 LiveExecutor 是否把下单/平仓
    # 委托给 LivePositionManager（true=LPM 记账；false=直发交易所、**账本不更新**）。
    # 此前既没写进 .env 也未登记 ⇒ 默认 false 且无人可见（"开实盘"与"要记账"被拆散了）。
    # 注：刻意**不**放进 SAFETY_CRITICAL_FLAGS —— 它的当前值就是 false（本机跑 paper），
    # 放进去会让启动日志每次都报"安全关键 flag 被关闭"，把噪音当信号。
    "LIVE_SUB_POSITION_TRACKING",
    "LIVE_MODE_RISK_GUARDED",
    "LIVE_ORCHESTRATOR_HARD_GATE",
    "LIVE_SCALP_VETO_FAIL_OPEN",
    "LLM_ANALYSIS_FORCE_STREAM",
    "LLM_CACHE_THRESHOLD",
    "LLM_CACHE_TTL_SECONDS",
    "LLM_CALL_TIMEOUT_DEEP_SECONDS",
    "LLM_CALL_TIMEOUT_SECONDS",
    "LLM_BUDGET_ENABLED",
    "LLM_BUDGET_MASTER",
    "LLM_BUDGET_MIDLONG",
    "LLM_BUDGET_OTHER",
    "LLM_BUDGET_SCALP",
    "LLM_BUDGET_WAIT_MASTER",
    "LLM_BUDGET_WAIT_MIDLONG",
    "LLM_BUDGET_WAIT_OTHER",
    "LLM_BUDGET_WAIT_SCALP",
    "LLM_DISABLE_STREAMING",
    "LLM_GLOBAL_MAX_CONCURRENT",
    "LLM_MAX_CALLS_PER_CYCLE",
    "LLM_REASONING_USE_STREAM",
    "LLM_SEMANTIC_CACHE_ENABLED",
    # [2026-09-16 调研轮11] 本地 Ollama 停用（true=一律走线上；false=恢复本地优先+云端降级）
    "LLM_LOCAL_FIRST_DISABLED",
    "LLM_SEMAPHORE_WAIT_SECONDS",
    "LLM_STREAM_MAX_TOKENS",
    "LLM_STREAM_PROMPT_CHARS",
    "LLM_STREAM_SAFETY_CAP_SECONDS",
    "LOCAL_LLM_API_KEY",
    "LOCAL_LLM_BASE_URL",
    "LOCAL_LLM_CONFIG_ID",
    "LOCAL_LLM_MODEL",
    "LOCAL_LLM_NAME",
    "LOG_ALARM_ON_MISSING_NATURE",
    "LUNARCRUSH_API_KEY",
    "MACRO_REGIME_BLOCK_TREND_LONG_CONF",
    "MACRO_REGIME_CONF_EMA_ALPHA",
    "MACRO_REGIME_MIN_HOLD_HOURS",
    "MACRO_REGIME_SWITCH_THRESHOLD",
    "MACRO_REGIME_TRANSITION_HOLD_HOURS",
    "MAINT_MARGIN_RATIO",
    "MANUAL_SYMBOL_LEVERAGE_CAP",
    "MAP_ELITES_ENABLED",
    "MAP_ELITES_MODE",
    "MARKET_DATABASE_URL",
    "MARKET_DATA_BATCH_WRITE_ENABLED",
    "MARKET_DATA_HTTP_PROXY",
    "MARKET_DATA_QUEUE_ENABLED",
    "MARKET_DATA_QUEUE_WORKERS",
    "MARKET_DATA_QUOTE_EXCHANGES",
    "MARKET_DATA_V2_ENABLED",
    "MARKET_DATA_V2_EXCHANGES",
    "MARKET_DATA_V2_LIMIT",
    "MARKET_DATA_V2_SCHEDULER_ENABLED",
    "MARKET_DATA_V2_SCHEDULER_INTERVAL",
    "MARKET_DATA_V2_SYMBOLS",
    "MARKET_DATA_V2_TIMEFRAMES",
    "MARKET_DATA_VERIFIER_ENABLED",
    "MASTER_CLOSE_MIN_PROFIT_PCT",
    "MASTER_CLOSE_TINY_DISABLED_TIERS",
    "MASTER_LLM_MAX_RETRIES",
    "MASTER_LLM_MAX_TOKENS",
    "MASTER_MIDLONG_LLM_MODE",
    "MASTER_REDUCE_MIN_LOSS_PCT",
    "MENTAL_FROZEN_COOLDOWN_MINUTES",
    "MENTAL_FROZEN_PROBE_SIZE_MULT",
    "MENTAL_HIGH_CONF_FROZEN_BYPASS",
    "MENTAL_LOSS_TO_CAUTIOUS",
    "MENTAL_LOSS_TO_FROZEN",
    "AI_DECISION_CALIBRATOR_CACHE_TTL_SEC",
    "AI_DECISION_CALIBRATOR_ENABLED",
    "AI_DECISION_CALIBRATOR_LOOKBACK_DAYS",
    "AI_DECISION_CALIBRATOR_MIN_BUCKET",
    "AI_DECISION_CALIBRATOR_MIN_SAMPLES",
    "MIDLONG_ACTIVATION_ENABLED",
    "MIDLONG_ACTIVE_EXIT_ENABLED",
    "MIDLONG_ACTIVE_FACTOR_MAX",
    "MIDLONG_ACTIVE_RETIRE_ABS_IC",
    "MIDLONG_AGENT_INDEPENDENT_SCHEDULER",
    "MIDLONG_AGENT_SL_TO_EXECUTE",
    "MIDLONG_AI_MANDATORY",
    "MIDLONG_ALLOW_RANGE_PROBE",
    "MIDLONG_AST_BRIDGE_DEDUP",          # 轮105：AST 同族去重（默认 true）
    "MIDLONG_AST_BRIDGE_MAX",
    "MIDLONG_BELIEF_LOOP_ENABLED",
    "MIDLONG_NIBBLE_PROBE_DAILY_MAX",
    "MIDLONG_NIBBLE_PROBE_ENABLED",
    "MIDLONG_NIBBLE_PROBE_MARGIN_MULT",
    "MIDLONG_PAPER_PROBE_ON_WAIT",
    "MIDLONG_CALIBRATOR_ENABLED",
    "MIDLONG_DIRECTION_CONSISTENCY_ENABLED",
    "MIDLONG_EV_ENFORCE_REQUIRES_CALIBRATION",
    # [P7 执行 2026-09-10] swing(mid) 赛道 EV 硬拦开关（默认 false）
    "MIDLONG_EV_ENFORCE_MID",
    # [2026-09-11] paper 下 mid 赛道 EV 影子放行（收集样本；live 硬拦不变，默认 true）
    "MIDLONG_EV_ENFORCE_MID_PAPER_ALLOW",
    # [M1 2026-09-14] long 车道 EV 硬拦开关（默认 false=paper 影子放行，live 硬拦不变）
    "MIDLONG_EV_ENFORCE_LONG",
    # [M1 2026-09-14] paper 下 long 车道 EV 影子放行（默认 true）
    "MIDLONG_EV_ENFORCE_LONG_PAPER_ALLOW",
    "MIDLONG_EV_FALLBACK_RR",
    "MIDLONG_EV_GATE_ENABLED",
    "MIDLONG_EXEC_AUTHORITY",
    "MIDLONG_EXIT_INVALIDATE_CONF",
    "MIDLONG_EXIT_MIN_HOLD_SEC",
    "MIDLONG_FACTOR_RESEARCH_ENABLED",
    "MIDLONG_HUB_BUILD_PAPER",
    "MIDLONG_HUB_NIBBLE_PAPER",
    "MIDLONG_HUB_TREND_SIGNAL_BONUS",
    "MIDLONG_HUB_WAIT_PAPER",
    "MIDLONG_MASTER_DELEGATE",
    "MIDLONG_MASTER_STAGGER_SEC",
    "MIDLONG_MID_VIA_MLTO",
    "MIDLONG_MID_VIA_FACTOR_ROUTE",
    # [M5 2026-09-14] 因子路由 A/B 车道（脑开启时 paper 并行自开；false=旧行为）
    "MIDLONG_MID_FACTOR_ROUTE_AB",
    # [2026-09-16 调研轮7] mid 4h 单周期反转离场开关（false=回滚到双周期复查）
    "MIDLONG_MID_4H_REVERSAL_EXIT",
    "MIDLONG_BRAIN_MODE",
    "MIDLONG_THESIS_TTL_MID_S",
    "MIDLONG_THESIS_TTL_LONG_S",
    "MIDLONG_THESIS_FAIL_BACKOFF_MID_S",
    "MIDLONG_THESIS_FAIL_BACKOFF_LONG_S",
    "MIDLONG_WATCH_SHOCK_PCT_MID",
    "MIDLONG_WATCH_SHOCK_PCT_LONG",
    "MIDLONG_WATCH_CHASE_PCT_MID",
    "MIDLONG_WATCH_CHASE_PCT_LONG",
    "MIDLONG_WATCH_NEAR_INV_PCT",
    "MIDLONG_WATCH_MIN_REFRESH_S",
    "MIDLONG_NO_THESIS_NO_OPEN",
    "MIDLONG_CHART_REQUIRED",
    "MIDLONG_THESIS_MAX_REFRESH_PER_CYCLE",
    "MIDLONG_THESIS_WATCH_REFRESH_CAP",
    "THESIS_SHADOW_ENABLED",
    "COMMITTEE_SHADOW_ENABLED",
    "LONG_TREND_V2",
    "FACTOR_ROUTE_MIN_ACTIVE_FACTORS",
    "FACTOR_ROUTE_AST_IC_CAP",           # 轮105：AST 桥接 ic_mean(实为ICIR) 幅度封顶
    "CONTEXT_PACK_FACTORS_ENABLED",      # 轮107：主脑上下文因子层开关
    "MIDLONG_MIN_SIZE_MULT",             # 轮108：缩仓链地板（低于则诚实拒绝）
    "MIDLONG_MID_FACTOR_ROUTE_SHADOW",   # 轮109：因子路由影子档（只决策不开仓）
    "FACTOR_CRITIC_ENABLED",
    "FACTOR_CRITIC_MODEL",
    "FACTOR_ROUTE_ENTRY_THRESHOLD",
    "FACTOR_ROUTE_IC_ABS_MIN",
    "FACTOR_ROUTE_KLINE_EXCHANGE",
    "FACTOR_ROUTE_SL_ATR_MULT",
    "FACTOR_ROUTE_TP_ATR_MULT",
    "FACTOR_ROUTE_SL_PCT",
    "FACTOR_ROUTE_TP_PCT",
    "FACTOR_ROUTE_TRANCHE_MARGIN_PCT",
    "MIDLONG_MLTO_CONTROLS_EXEC",
    "MIDLONG_MONTE_CARLO_ENABLED",
    "MIDLONG_MTF_CONFLICT_MULT",
    "MIDLONG_MTF_ENFORCE_ENABLED",
    "MIDLONG_MTF_STRONG_CONF",
    "MIDLONG_OPEN_READINESS_MIN_LONG",
    "MIDLONG_OPEN_READINESS_MIN_MID",
    "MIDLONG_ORCH_SNAPSHOT_V2",
    "MIDLONG_ORCH_STALE_REFRESH_SEC",
    "MIDLONG_PAPER_PROBE_STRICT",
    "MIDLONG_PERSISTENCE_TICKS",
    "MIDLONG_POSITION_MGMT_PYRAMID_DIRECT_PNL",
    "MIDLONG_QUANT_BRIEF_ENABLED",
    "MIDLONG_QUANT_BRIEF_HARD_GATE",
    "MIDLONG_QUANT_BRIEF_IN_PROMPT",
    "MIDLONG_ROUTE_TREND_INVERT_AST",    # 轮105：反转类 AST 因子纳入趋势反号（默认 true）
    "MIDLONG_ROUTE_TREND_INVERT_REVERSAL",
    "MIDLONG_SCAN_BATCH",
    "MIDLONG_STABLE_MIN_AGREE",
    "MIDLONG_STABLE_WINDOW",
    "MIDLONG_THESIS_DEBATE_ENABLED",
    "MIDLONG_THESIS_LEDGER_ENABLED",
    "MIDLONG_THESIS_OPEN_GATE",
    "MIDLONG_THESIS_REGIME_RESET",
    "MIDLONG_THESIS_STABLE_MIN_SEC_LONG",
    "MIDLONG_THESIS_STABLE_MIN_SEC_MID",
    "MIDLONG_THESIS_STALE_MAX_SEC",
    "MIDLONG_TIGHTEN_PROFIT_FLOOR",
    "MIDLONG_TIGHTEN_SL_FLOOR",
    # [2026-09-18 轮96 修 Fix B] 车道最小收紧带宽（追踪止损与现价的距离下限）
    "MIDLONG_TIGHTEN_MIN_BAND_PCT_LONG",
    "MIDLONG_TIGHTEN_MIN_BAND_PCT_MID",
    "MIDLONG_TIGHTEN_MIN_BAND_PCT_SHORT",
    # [轮96 Fix C] 拒付追踪派生止损后的回退位「最小锁定利润」
    "MIDLONG_MIN_LOCK_PROFIT_PCT_LONG",
    "MIDLONG_MIN_LOCK_PROFIT_PCT_MID",
    "MIDLONG_MIN_LOCK_PROFIT_PCT_SHORT",
    # [轮99] 趋势车道跳过"中短线口径"日内保护块（分段止盈/保本/回撤/追踪 + ExitPolicy 层）
    "EXIT_TREND_LANE_SKIP_INTRADAY",
    # [轮103] 长线车道独占动作流水线（跳过 7 条中线专属路径；false=回滚到轮99）
    "EXIT_TREND_LANE_OWN_PIPELINE",
    # [轮100] 中线 / 长线**分车道**配置（复查节奏、入场止损 ATR 倍数）
    # 原为两车道共用键 MIDLONG_POSITION_MGMT_LLM_INTERVAL_SEC / MIDLONG_ATR_SL_MULT，
    # 现已拆开车道专属键（默认值 = 原共用值，行为不变）。真源见 config/lane_policy.py。
    "MIDLONG_POSITION_MGMT_LLM_INTERVAL_SEC_MID",
    "MIDLONG_POSITION_MGMT_LLM_INTERVAL_SEC_LONG",
    "MIDLONG_ATR_SL_MULT_MID",
    "MIDLONG_ATR_SL_MULT_LONG",
    # [轮101] 风险标尺（**刻意不按车道**：宽止损必须换来缩仓，风险才守恒）
    "MIDLONG_RISK_REF_ATR_MULT",
    "MIDLONG_TRANCHE_ENTRY_ENABLED",
    "MLTO_AI_GOVERNED",
    "MLTO_AI_GOVERNED_WEIGHT",
    "MLTO_LLM_WEIGHT_LONG",
    "MLTO_LLM_WEIGHT_MID",
    "MLTO_LONG_MAX_SL",
    "MLTO_LONG_MAX_TP",
    "MLTO_LONG_MIN_SL",
    "MLTO_LONG_MIN_TP",
    "MLTO_MID_MAX_SL",
    "MLTO_MID_MAX_TP",
    "MLTO_MID_MIN_SL",
    "MLTO_MID_MIN_TP",
    "ML_ACTIVATION_DEBOUNCE_SEC",
    "ML_LIVE_RETRAIN_HOURS",
    "ML_MODEL_DIR",
    "ML_MODEL_TYPE",
    "ML_PIPELINE_ENABLED",
    "MULTI_VENUE_FUNDING_ALERT_THRESHOLD",
    "MULTI_VENUE_FUNDING_COLLECTOR_ENABLED",
    "MULTI_VENUE_FUNDING_COLLECT_INTERVAL_SECONDS",
    "MULTI_VENUE_FUNDING_SYMBOLS",
    "MULTI_VENUE_FUNDING_VENUES",
    "NSGA2_ENABLED",
    # [2026-08-24 槽位治理] 本地 Ollama 全局并发槽数（重负载调用方另有单调用方上限）
    "OLLAMA_MAX_CONCURRENT",         # 默认 4（实测真并行度约 4，再高只排队）
    "OLLAMA_HEAVY_CALLER_SLOTS",     # 单个重调用方的槽上限（默认 2 = 全局的一半）
    "OLLAMA_SLOT_WAIT_SEC",          # 抢槽等待秒数（默认 3；等久了不如降级云端）
    "OLLAMA_CALL_TIMEOUT_SEC",       # 高频短调用的超时上限（默认 8s，用于快速降级云端）
    "OLLAMA_DEEP_CALL_TIMEOUT_SEC",  # 深度分析调用的超时上限（默认 300s；8s 会掐断长输出）
    "OPENAI_API_KEY",
    "OPENCODE_AGENT_BUILD",
    "OPENCODE_AGENT_PLAN",
    "OPENCODE_AGENT_REVIEW",
    "OPENCODE_AUTO_APPLY_MINOR",
    "OPENCODE_AUTO_REVIEW",
    "OPENCODE_BRIDGE_TRANSPORT",
    "OPENCODE_CLI_PATH",
    "OPENCODE_CODEGEN_ENABLED",
    "OPENCODE_ENABLED",
    "OPENCODE_MAJOR_ALERT_CHANNELS",
    "OPENCODE_MAJOR_ALERT_COOLDOWN_S",
    "OPENCODE_MAJOR_AUTO_APPLY",
    "OPENCODE_MAJOR_CREATE_PROPOSALS",
    "OPENCODE_MAJOR_PACE_DOWNSHIFT_STEPS",
    "OPENCODE_MAJOR_PACE_FLOOR",
    "OPENCODE_MODEL",
    "OPENCODE_MULTI_ROUND_TIMEOUT_S",
    "OPENCODE_PATCH_MAX_DELTA_PCT",
    "OPENCODE_PENDING_DRAIN_LIMIT",
    "OPENCODE_PENDING_DRAIN_ON_STARTUP",
    "OPENCODE_PENDING_DRAIN_ROUNDS",
    "OPENCODE_REQUEST_TIMEOUT_S",
    "OPENCODE_REVIEW_DEFER_RETRY_S",
    "OPENCODE_REVIEW_MIN_CONFIDENCE",
    "OPENCODE_REVIEW_MODEL",
    "OPENCODE_REVIEW_TIMEOUT_S",
    "OPENCODE_SERVER_URL",
    # [2026-09-16 调研轮12] sidecar 轮换间隔（0=不轮换；默认 60）
    "OPENCODE_RECYCLE_EVERY",
    "OPENCODE_SHADOW_ENABLED",
    "OPENCODE_SHADOW_PORT",
    "OPENCODE_SIDECAR_AUTOSTART",
    "OPENCODE_SMALL_MODEL",
    "OPENCODE_VALIDATION_HOURS",
    "OPENCODE_VALIDATION_USE_PACE",
    "ORCHBG_CACHE_FRESH_SEC",
    "ORCHESTRATOR_HARD_GATE",
    "ORCHESTRATOR_WAIT_OVERRIDE_CONF",
    "ORCH_BG_INTERVAL_SEC",
    "ORCH_MID_INDEPENDENT_TRIGGER",
    "PAPER_AUTO_COIN_EXPIRY_KEEP_SCORE",
    "PAPER_AUTO_COIN_PREFLIGHT_RELAX",
    "PAPER_AUTO_COIN_REPLACEMENT_MARGIN",
    "PAPER_AUTO_COIN_ROTATE",
    "PAPER_AUTO_COIN_SCORE_V3",
    "PAPER_AUTO_COIN_UNIVERSE_MIN_SIZE",
    "PAPER_AUTO_COIN_UNIVERSE_SOFT",
    "PAPER_AUTO_COIN_V5_CONF_PENALTY",
    "PAPER_AUTO_COIN_V5_MIN_RR",
    "PAPER_DEFAULT_BALANCE",
    "PAPER_DISABLE_LOSS_LOCKS",
    "PAPER_FAST_TRIAL",
    "PAPER_MAX_ACTIVE_STRATEGIES_PER_SYMBOL",
    "PAPER_MODE",
    "PAPER_NETTING_MODE",
    "PAPER_ONE_WAY_REVERSE_NETTING",
    "PAPER_PACE_DEFAULT_GEAR",
    "PAPER_PACE_EVAL_INTERVAL_S",
    "PAPER_PACE_SYMMETRIC_CLOSE",
    "PAPER_RELAX_AUTO_COIN_V5",
    "PAPER_SCALP_UNIVERSE_DEGRADED_SOFT",
    "PAPER_SCALP_UNIVERSE_DEGRADED_SIZE_MULT",
    "PAPER_SCALP_MICRO_SOFT",
    "PAPER_SCALP_MICRO_SOFT_PENALTY",
    "PAPER_SCALP_ADAPTIVE_LOSS_CEILING",
    "PAPER_SCALP_ADVISORY_PENALTY_MULT",
    "PAPER_RISK_GATE_ENABLED",
    "PAPER_SIMULATION_TIER",
    "PAPER_SKIP_STRATEGY_TERMINATE",
    "PAPER_TREND_MIN_SCORE_TO_OPEN",
    "PARITY_SCORE_ENABLED",
    "PBO_AUDIT_ENABLED",
    "PBO_REJECT_THRESHOLD",
    "PERFORMANCE_GATE_ENABLED",
    "PERFORMANCE_GATE_MIN_SAMPLES",
    "PERFORMANCE_GATE_MIN_WR",
    "PERFORMANCE_GATE_TTL_HOURS",
    "PGPASSWORD",
    "PG_TARGET_URL",
    "PORTFOLIO_MAX_CORRELATION_RISK",
    "PORTFOLIO_MAX_RISK",
    "PORTFOLIO_MAX_SINGLE_POSITION",
    "PORTFOLIO_RISK_HARD_BLOCK",
    "POSITION_MIN_DECISION_INTERVAL",
    "PRESCREENER_ENABLED",
    "PROFIT_PROTECTION_ACTIVATION_USD",
    "PROFIT_PROTECTION_DRAWDOWN",
    "PROFIT_PROTECTION_EMERGENCY",
    "PROFIT_PROTECTION_MIN_HOLD_SEC",
    "PROFIT_PROTECTION_VERSION",
    "PROMOTION_GATE_ENABLED",
    "PROMOTION_SCAN_DEBOUNCE_SEC",
    "PROMPT_EVOLUTION_ENABLED",
    "PROMPT_TRAINING_AB_ENABLED",
    "PYTHONDONTWRITEBYTECODE",
    "PYTHONPATH",
    "QAA_ANALYST_STREAM_SAFETY_CAP_S",
    "QAA_ANALYST_TIMEOUT_MAX_S",
    "QAA_ANALYST_TIMEOUT_S",
    "QAA_CAPTURE_UNIFIED_SNAPSHOT",
    "QAA_CHROMA_DIR",
    "QAA_DEEP_ANALYSIS_EVERY_N_TICKS",
    "QAA_DEEP_COST",
    "QAA_DEEP_MAX_TOKENS",
    "QAA_DEEP_MODEL",
    "QAA_DEEP_TEMPERATURE",
    "QAA_DEEP_TIMEOUT",
    "QAA_EMBEDDING_BACKEND",
    "QAA_EMBEDDING_MODEL",
    "QAA_ENABLED_AGENTS",
    "QAA_KNOWLEDGE_BACKEND",
    "QAA_KNOWLEDGE_DIR",
    "QAA_KNOWLEDGE_SCOPE",
    "QAA_MODE",
    "QAA_OPTIMIZER",
    "QAA_QUICK_COST",
    "QAA_QUICK_MAX_TOKENS",
    "QAA_QUICK_MODEL",
    "QAA_QUICK_TEMPERATURE",
    "QAA_QUICK_TIMEOUT",
    "QAA_READ_SNAPSHOT_STORE",
    "QAA_RERANKER_BACKEND",
    "QAA_RERANKER_ENABLED",
    "QAA_SEMANTIC_MEMORY_ENABLED",
    "QAA_SNAPSHOT_TIMEOUT_S",
    "QAA_TICK_BUDGET_MS",
    "QAA_V3_ENABLED",
    "RATE_LIMIT_ENABLED",
    "RATE_LIMIT_LLM_APIKEY",
    "RATE_LIMIT_LLM_GENERATE",
    "RATE_LIMIT_TRADING",
    "REBATE_EXECUTION_LLM_MAX_TOKENS",
    "REBATE_PROPOSAL_MIN_SAMPLE_N",
    "REBATE_QAA_DEEP_TIMEOUT_MS",
    "REBATE_QAA_QUICK_TIMEOUT_MS",
    "REBATE_STRATEGY_LLM_MAX_TOKENS",
    "REDIS_URL",
    "REDUCE_MAX_COUNT",
    "REENTRY_COOLDOWN_SECONDS",
    "REENTRY_MIN_COOLDOWN_AFTER_TP_SEC",
    "REPLAY_RATIO",
    "RESOURCE_GUARD_ENABLED",
    "RISK_AI_REVERSE_MICRO_LOSS_MIN_CONF",
    "RISK_AI_REVERSE_MICRO_LOSS_PCT",
    "RISK_AI_REVERSE_MIN_CONF",
    "RISK_ENGINE_ENABLED",
    "RISK_MASTER_SWITCH_ENABLED",
    "RISK_P2_ENABLED",
    "RISK_P3_AI_REVERSE_COOLDOWN_SEC",
    "RISK_P3_DECISION_LOG_ENABLED",
    "RISK_P3_ENABLED",
    "RISK_P3_MASTER_CLOSE_REQUIRES_HARDFACT",
    "RISK_STAGE_E_ENABLED",
    "RISK_USE_LEVERAGE_CAP_BY_TIER",
    "RISK_USE_LONG_TIER_1D_ATR",
    "RISK_USE_LONG_TIER_IMMUNE",
    "RISK_USE_LONG_TIER_STAGED_TP",
    "RISK_USE_NATURE_EXIT_ORCHESTRATOR",
    "RISK_USE_TIER_PROMPT_HINTS",
    "RISK_USE_TIER_TP_SL_V2",
    "RISK_USE_VOL_BAND_ATR_MULT",
    "RISK_USE_VOL_BAND_DEFAULTS",
    "RISK_USE_VOL_BAND_X_HIGH",
    "RL_DECISION_ENABLED",
    "RL_SHADOW_ONLY",
    "RULE_SYNC_ENABLED",
    "RULE_SYNC_INTERVAL_SECONDS",
    "RUNTIME_GOVERNOR_AUTO_APPROVE_PAPER",
    "RUN_DB_MAINTENANCE_ON_STARTUP",
    "RUN_MAIN",
    "SCALP_ACTIVE_FACTOR_MAX",
    "SCALP_ACTIVE_RETIRE_ABS_IC",
    "SCALP_AI_REVERSE_DISABLED",
    "SCALP_ALLOW_COUNTER_TREND",
    "SCALP_CALIBRATOR_CACHE_TTL_SEC",
    "SCALP_CALIBRATOR_ENABLED",
    "SCALP_CALIBRATOR_LOOKBACK_DAYS",
    "SCALP_CALIBRATOR_MIN_CORR",
    "SCALP_CALIBRATOR_MIN_SAMPLES",
    "SCALP_CALIBRATOR_SAMPLE_SINCE",
    "SCALP_COUNTER_TREND_SIZE_MULT",
    "SCALP_DIRECT_THRESHOLD",
    "SCALP_EV_COLD_START_ALLOWANCE_PCT",
    "SCALP_EV_GATE_ENABLED",
    "SCALP_EV_MIN_PCT",
    "SCALP_EV_FAIL_CLOSED_LIVE",
    "SCALP_EV_SL_REALIZATION",
    "SCALP_EV_TP_REALIZATION",
    "SCALP_EXECUTION_LANE_ENABLED",
    "SCALP_GATE_DEFER_REGIME_TO_V5",
    "SCALP_DAILY_OPEN_CAP",
    "SCALP_FACTOR_CANDLE_SEC",
    "SCALP_FACTOR_CONFIRM_THRESHOLD",
    "SCALP_FACTOR_EXECUTE_THRESHOLD",
    "SCALP_FACTOR_IC_EVAL_EVERY_N_TICKS",
    "SCALP_FACTOR_INDEPENDENT_SCHEDULER",
    "SCALP_FACTOR_SCAN_INTERVAL_SEC",
    "SCALP_FUSION_ENABLED",
    "SCALP_FUSION_MAX_DELTA",
    "SCALP_FUSION_MIN_CALIBRATION",
    "SCALP_LIQ_MAGNET_OPEN_DISABLED",
    "MASTER_SCALP_EXIT_WHITELIST",
    "SCALP_MASTER_HARD_BLOCK",
    "SCALP_OPEN_DISABLED",
    "SCALP_MAX_OPENS_PER_TICK",
    "SCALP_META_COST",
    "SCALP_META_DEDUP_SEC",
    "SCALP_META_FEATURE_FREQ",
    "SCALP_META_FOLDS",
    "SCALP_META_GATE_AUC",
    "SCALP_META_HORIZON_SEC",
    "SCALP_META_MIN_PER_CLASS",
    "SCALP_META_MIN_SAMPLES",
    "SCALP_MICROSTRUCTURE_GUARD_ENABLED",
    "SCALP_MICRO_GUARD_STRICT",
    "SCALP_MR_COLD_BASE_RATE",
    "SCALP_MR_EV_TP_REALIZATION",
    "SCALP_MR_HIGH_BAND",
    "SCALP_MR_LOW_BAND",
    "SCALP_MR_MAX_RANGE_PCT",
    "SCALP_MR_MIN_RANGE_PCT",
    "SCALP_MR_MIN_RR",
    "SCALP_MR_MIN_TP",
    "SCALP_MR_RSI_OB",
    "SCALP_MR_RSI_OS",
    "SCALP_MR_TP_RANGE_FRAC",
    "SCALP_MR_TREND_VETO_ENABLED",
    "SCALP_MTF_CONFLICT_MULT",
    "SCALP_MTF_ENFORCE_ENABLED",
    "SCALP_MTF_HARD_ONLY_ANCHOR",
    "SCALP_MTF_RESONANCE_ENABLED",
    "SCALP_MTF_STRONG_CONF",
    "SCALP_OPEN_COOLDOWN_SEC",
    "SCALP_OPEN_SAME_SIDE_COOLDOWN_SEC",
    "SCALP_ORCH_CONFLICT_MIN_SCORE",
    "SCALP_PROFILE_LOG",
    "SCALP_RANGE_MAX_LONG",
    "SCALP_RANGE_MIN_SHORT",
    "SCALP_RANGING_SIZE_FLOOR",
    "SCALP_RANGING_MR_ENABLED",
    "SCALP_REVERSE_SOFT_VETO_MULT",
    "SCALP_SIGNAL_LOG_ENABLED",
    # ── [2026-09-03 v3 Phase 0] 止血 / 账本 ──
    "SCALP_SHADOW_MODE",
    "MIDLONG_OPEN_SHORT_ENABLED",
    "MIDLONG_SHORT_MODE",
    "FEE_BUDGET_DAILY_PCT",
    "EDGE_LEDGER_ACCOUNTS",
    "EXIT_FEE_BUDGET_PCT",
    # ── [2026-09-03 v3 方向7] RiskEngine 单入口 / TradingState / 急停 / 熔断 ──
    "RISK_ENGINE_V3_ENABLED",        # 默认 true；false=只记录不拦截（观察模式）
    "RISK_DAILY_QUOTA_ENABLED",      # 默认 true；日开仓配额（单一来源 runtime_tuning）
    "LIVE_KILL_SWITCH",              # 部署级急停（true=实盘新开仓全拒）
    "LIVE_KILL_SWITCH_SCOPE",        # live（默认）| all（paper 也拦）
    "RISK_COMMAND_TOKEN",            # /api/ops/risk/* 写操作与飞书命令回调的共享令牌
    "RISK_CONNECTIVITY_FAIL_THRESHOLD",  # 连续失败阈值（默认 3）
    "RISK_CONNECTIVITY_COOLDOWN_SEC",    # 熔断冷却（默认 600）
    "RISK_FLASH_CRASH_1H_PCT",       # BTC 1h 跌幅阈值（默认 8）
    "RISK_FLASH_CRASH_4H_PCT",       # BTC 4h 跌幅阈值（默认 12）
    "RISK_FLASH_CRASH_REDUCING_HOURS",   # 闪崩后 REDUCING 持续小时（默认 24）
    "RISK_DD_HALVE_PCT",             # 组合回撤减半档（默认 20）
    "RISK_DD_REDUCING_PCT",          # 组合回撤只平不开档（默认 30）
    # ── [2026-09-03 v3 方向6] 统一告警通道（飞书沿用 notification_config.json）──
    "ALERT_TELEGRAM_BOT_TOKEN",
    "ALERT_TELEGRAM_CHAT_ID",
    "ALERT_WEBHOOK_URLS",            # 逗号分隔的通用 webhook（POST JSON）
    "ALERT_DEDUPE_SEC",              # 同 dedupe_key 去重窗口（默认 600）
    "ALERT_P0_DEDUPE_SEC",           # P0 去重窗口（默认 120）
    "ALERT_P2_ALL_CHANNELS",         # P2 也发全通道（默认 false，只飞书）
    # ── [2026-09-03 v3 方向4 p0-event-data] 免费事件数据接入 ──
    "EVENT_COLLECTORS_HOST",         # dc | main | both：事件采集任务在哪个进程执行（默认 dc 数据中心）
    "EVENTS_HTTPS_PROXY",            # 非 Binance 域（OKX/Bybit）的 HTTPS 代理；缺省退 HTTPS_PROXY
    "EVENTS_HTTP_DIRECT",            # =1 全部直连（不走任何代理）
    "BINANCE_WEIGHT_SOFT_LIMIT",     # 事件采集器共享的 Binance 1 分钟权重软上限（默认 1500/2400，超过即等下一分钟）
    "BINANCE_EVENTS_MIN_INTERVAL_SEC",  # 事件采集器 Binance 请求最小间隔（默认 0.15s）
    "FUNDING_BACKFILL_SLEEP_SEC",    # fundingRate 回填每请求间隔（默认 0.65s；该端点 500 次/5 分钟独立限额）
    "LIQUIDATION_STREAM_ENABLED",    # 清算 WebSocket 常驻（默认 true）
    "LIQUIDATION_STREAM_SOURCES",    # 清算源列表（默认 binance,asterdex,okx,bybit；Binance 期货流在部分网络静默）
    "BYBIT_LIQ_TOP_N",               # Bybit allLiquidation 订阅币数（24h 成交额 Top-N，默认 60）
    "LIQ_SILENT_WARN_SEC",           # 已连接但无帧多久标记 silent 并告警（默认 900）
    "LIQ_LARGE_TICK_USD",            # 单笔大额清算事件阈值（默认 250000）
    "LIQ_CASCADE_5M_MAJOR_USD",      # BTC/ETH 5 分钟级联阈值（默认 1e7）
    "LIQ_CASCADE_5M_USD",            # 其它币 5 分钟级联阈值（默认 2e6）
    "LIQ_CASCADE_5M_MARKET_USD",     # 全市场 5 分钟级联阈值（默认 5e7）
    "LIQ_TICKS_RETENTION_DAYS",      # 逐笔清算保留天数（默认 30）
    "POSITION_STRUCTURE_TOP_N",      # 持仓结构币池：24h 成交额 Top-N（默认 60）∪ 核心币
    "POS_OI_JUMP_PCT",               # 1h OI 名义变动事件阈值 %（默认 8）
    "FUNDING_EXTREME_8H",            # 极端资金费阈值（8h 口径，默认 0.001 = 0.1%）
    "NEWS_HIGH_IMPACT_MIN",          # 新闻桥接最低强度（量纲 1–5，默认 4）
    "WHALE_LARGE_USD",               # 巨鲸桥接最低金额（默认 5e7）
    "BRIDGE_LOOKBACK_HOURS",         # 桥接回看窗口小时（默认 6）
    "RISK_EVENT_WINDOWS_ENABLED",    # RiskEngine 事件避险窗口检查（默认 true）
    "RISK_EVENT_NEWS_BLOCK",         # 负面强新闻禁开多（默认 false，待 E5-5 影子验证）
    # ── [v3 方向2 p0-model-gateway] ModelGateway / QuotaGuard / 深度分析 ──
    "MODEL_GATEWAY_RETRY_COUNT",     # [2026-09-11] 连接类失败重试次数（默认 1，0=不重试）
    "MINIMAX_API_KEY",               # MiniMax Token Plan 订阅 Key（Anthropic 兼容 API 直连）
    "MINIMAX_BASE_URL",              # 默认 https://api.minimax.io/anthropic
    "MINIMAX_MODEL",                 # 默认 MiniMax-M3（可 MiniMax-M2.7）
    "MINIMAX_HTTPS_PROXY",           # MiniMax 直连专用代理；缺省退 EVENTS_HTTPS_PROXY → HTTPS_PROXY
    "ZAI_CODING_PLAN_API_KEY",       # GLM Coding Plan Key（只给 OpenCode sidecar 的 zai-coding-plan provider；后端不直连）
    "GLM_OPENCODE_MODEL",            # sidecar 模型 slug（默认 zai-coding-plan/glm-5.3）
    "GLM_OPENCODE_AGENT",            # sidecar agent（默认 analysis：只读、纯 JSON）
    "DEEPSEEK_MODEL",                # 仲裁票 env 兜底模型（默认 deepseek-v4-flash；优先用租户 deep_analysis 用途配置）
    "ANALYSIS_PRIMARY_TRANSPORTS",   # 两条主传输（默认 minimax,glm_opencode）
    "ANALYSIS_ARBITER_TRANSPORT",    # 第三票（默认 deepseek）
    "ANALYSIS_FALLBACK_TRANSPORTS",  # 主票缺席时的顶替候选（默认 deepseek,ollama）
    "ANALYSIS_OLLAMA_MODEL",         # 本地票模型（默认 qwen3:14b）
    "ANALYSIS_OLLAMA2_MODEL",        # 第二条本地票模型（须与上一条不同，默认 qwen2.5:7b）
    "ANALYSIS_LOCAL_TRANSPORTS",
    # [2026-09-16 调研轮12] 传输鉴权失败冷却秒数（默认 600）
    "ANALYSIS_AUTH_COOLDOWN_SEC",     # 免配额的本地传输名单（默认 ollama,ollama2）
    # ── [2026-09-03 v3 方向1 p1-trend-engine] E1 趋势引擎 / PositionConstruction / ExitPolicy ──
    "TREND_CORE_SYMBOLS",            # E1 核心币（默认 BTC,ETH,SOL,BNB,XRP,DOGE,LINK,AVAX）
    "TREND_EXEC_LAG_DAYS",           # 实盘执行延迟天数（1 = 回测验证口径）
    "TREND_DATA_EXCHANGE",           # 日线数据源交易所（默认 binance）
    "TREND_WEIGHTING",               # equal | vol_target | portfolio_vol_target
    "TREND_VOL_TARGET",              # 趋势桶目标年化波动（0.35）
    "TREND_MAX_WEIGHT_PER_SYMBOL",   # 单币名义上限（0.35）
    "TREND_GROSS_CAP",               # 趋势车道总名义上限（1.0）
    "TREND_RISK_PER_TRADE_PCT",      # 单笔风险帽（长线 0.0125）
    "TREND_STOP_RATCHET",            # Chandelier 是否只上移（默认 false=回测口径）
    "TREND_ENTRY_RULE",              # ema_stack（回测验证）| l1_score（对照）
    "TREND_CHANDELIER_MULT",         # Chandelier 倍数（3.0）
    "TREND_ATR_PERIOD",              # ATR 窗口（20）
    "TREND_VOL_LOOKBACK",            # 实现波动窗口（60 日）
    "TREND_MAX_POSITIONS",           # 同时最多持仓数（8）
    "TREND_E1_ENABLED",              # E1 日任务是否真下单（false=只算目标 + 漂移）
    # [M2 2026-09-14] drift 杠杆违规阈值（默认 5.0=币种杠杆权威表上限；旧硬编码 3.0 与权威表冲突）
    "TREND_DRIFT_MAX_LEVERAGE",
    "TREND_E1_ACCOUNT_IDS",          # E1 执行的模拟账户 id（逗号分隔）
    "TREND_E1_BUCKET_FRACTION",      # 趋势桶占权益（E4 三桶 60/30/10 → 0.60）
    "TREND_E1_REBALANCE_TOL",        # 权重超目标多少才减仓（相对 0.25）
    "TREND_E1_DRY_RUN",              # 只打印动作
    "TREND_E1_ADOPT_LEGACY_LONGS",   # 接管核心币"应持"的存量非 E1 长仓（默认 true）
    "TREND_E1_LONG_LANE_EXCLUSIVE",  # E1 独占长车道（默认随 TREND_E1_ENABLED）
    # [2026-09-16 调研轮10] E1 独占的 AI 例外（AI 选出的长线标的可新开；false=完全独占）
    "TREND_E1_LONG_LANE_AI_EXCEPTION",
    "LIVE_LEVERAGE_FAIL_CLOSE",      # 实盘杠杆对齐失败即拒绝开仓（默认 true）
    "SYMBOL_LEVERAGE_ENABLED",       # 币种杠杆总开关（默认 true；关闭回落旧 requested 行为）
    "SYMBOL_LEVERAGE_MAP",           # 币种杠杆档位 "BTC:5,ETH:5,SOL:4"
    "SYMBOL_LEVERAGE_DEFAULT",       # 未列入币种的档位（默认 3）
    "POSITION_CONSTRUCTION_ENFORCE", # 仓位构造单一权威硬帽（默认 true）
    "PC_VOL_TARGET", "PC_MAX_WEIGHT_PER_SYMBOL", "PC_RISK_PER_TRADE_PCT", "PC_MAX_LEVERAGE", "PC_CLUSTER_CAP",
    # [调研轮26 2026-09-17] 按层覆盖（position_construction._lane_param 动态拼键：PC_<X>_<LANE> → PC_<X>）
    "PC_MAX_WEIGHT_PER_SYMBOL_LONG",
    "PC_MAX_WEIGHT_PER_SYMBOL_MID",
    "PC_GROSS_CAP", "PC_CONF_SCALE_MIN",  # 全局默认；PC_<PARAM>_<LANE> 按车道覆盖（见 KNOWN_FLAG_PATTERNS）
    "EXIT_POLICY_ENFORCE",           # ExitPolicy 车道声明层（默认 true）；EXIT_POLICY_<LANE>_<PARAM> 见 KNOWN_FLAG_PATTERNS
    # [2026-09-16 调研轮7] 存量仓随车道重标定刷新利润保护参数（止损字段保持快照值；false=回滚）
    "EXIT_POLICY_REFRESH_OPEN",
    "LIVE_NATIVE_TRAILING_STOP",     # live 侧 ExitPolicy trailing 激活时挂交易所原生 TRAILING_STOP_MARKET（默认 false）
    "ANALYSIS_UNIVERSE",             # context pack 币池（默认 BTC,ETH,SOL,BNB,XRP,DOGE,ADA,AVAX）
    "ANALYSIS_DEEP_DAILY_PER_MODEL",     # 深度任务每模型每日次数（默认 6）
    "ANALYSIS_EVENT_DAILY_PER_MODEL",    # 事件评估每模型每日次数（默认 20）
    "ANALYSIS_LIGHT_DAILY_PER_MODEL",    # 轻量/测试调用每模型每日次数（默认 40）
    "ANALYSIS_MAX_CONTEXT_TOKENS",       # 单次上下文上限（默认 60000）
    "ANALYSIS_MAX_OUTPUT_TOKENS",        # 单次输出上限（默认 4000）
    "ANALYSIS_5H_CALLS_PER_MODEL",       # 5 小时滚动窗每模型调用上限（默认 30；仅作未列入 MAP 的兜底）
    "ANALYSIS_WEEKLY_CALLS_PER_MODEL",   # 周滚动每模型调用上限（默认 150；同上）
    # [2026-09-04] 按传输覆盖：各家套餐差着数量级（GLM Max 每 5h 约 2400 次、
    # MiniMax Token Plan 实测 8 次仅耗 4%、DeepSeek 按量付费超额即账单），
    # 共用一个全局上限只能按最弱的定，等于把买来的高档额度锁在门外。
    "ANALYSIS_5H_CALLS_MAP",             # 形如 glm_opencode:400,minimax:100,deepseek:50
    "ANALYSIS_WEEKLY_CALLS_MAP",         # 形如 glm_opencode:2000,minimax:400,deepseek:250
    "ANALYSIS_DAILY_CALLS_MAP",          # 单传输每日总调用上限（与分类上限取较小者）
    "ANALYSIS_ALLOW_GLM_PEAK",           # 允许深度任务在 GLM 峰时（工作日 14–18 点，3× 消耗）运行（默认 false）
    "ANALYSIS_GLM_PEAK_TZ_OFFSET_H",     # 峰时/日界判定时区偏移小时（默认 8）
    # ── [v3 方向2 p1-deep-analysis] 双模型任务族 ──
    "ANALYSIS_TASKS_ENABLED",            # 日简报/周复盘/择时/事件评估总开关（默认 true）
    "ANALYSIS_WEEKLY_ENABLED",           # 周复盘定时（默认 false，研究报告不控仓）
    "ANALYSIS_TIMING_ENABLED",           # 择时定时（默认 false）
    "ANALYSIS_EVENT_LOOKBACK_HOURS",     # 事件扫描回看小时（默认 96）
    "ANALYSIS_EVENT_MIN_SEVERITY",       # 事件评估最低严重度（默认 3）
    "ANALYSIS_EVENT_BATCH_LIMIT",        # 每次扫描最多评估条数（默认 8；原 3）
    "AGENT_ANOMALY_INTERVAL_SEC",        # 异常 Agent 扫描间隔秒（默认 900）
    "ANALYSIS_EVENT_SCAN_SEC",           # 事件扫描间隔秒（默认 900）
    "ANALYSIS_TREND_CHART_SEC",          # 图审扫描间隔秒（默认 28800=8h）
    "ANALYSIS_TREND_CHART_FRESH_H",      # 已入账图审短于此时长则跳过（默认 8h）
    "ANALYSIS_TREND_CHART_MAX_PER_CYCLE",  # 单轮最多审几个币（默认 4）
    "MIDLONG_CHART_GATE_LOOKBACK_H",     # 开仓闸认图审的最长小时数（默认 16）
    # [P11 执行 2026-09-10] 图审信号/立场建议的时效上限（分钟）
    "MIDLONG_CHART_MAX_SIGNAL_AGE_MIN",  # 通用：超过即 fail-open 不否决（默认 240）
    "MIDLONG_CHART_ADVICE_TTL_MIN",      # 立场型建议（no_new_long/short）独立 TTL（默认 180，0=关闭特例）
    "MIDLONG_CHART_ADVICE_DIRECTION_CONSISTENT",  # [2026-09-11] 建议只在与信号方向相反时否决（默认 true）
    "MIDLONG_CHART_GATE_CONFLICT_STRENGTH",
    "MIDLONG_CHART_GATE_SUPPORT_STRENGTH",
    "MIDLONG_CHART_GATE_ENABLED",
    # ── [v3 方向5 p1-cashflow] E2 现金流 ──
    "CASHFLOW_ASTER_TE_ENABLED",         # Aster T&E 账本定时刷新
    "CASHFLOW_CARRY_SIM_ENABLED",        # 多场所 carry Paper 模拟
    "CASHFLOW_CARRY_NOTIONAL_USD",       # 模拟单腿名义（默认 500）
    "CASHFLOW_CARRY_MIN_NET_APR",        # 最低净 APR（默认 0.08）
    "CASHFLOW_CARRY_HORIZON_DAYS",       # 持有天数假设（默认 7）
    "CASHFLOW_CARRY_MAX_EXEC",           # 每次最多模拟几组 combo（默认 3）
    "CASHFLOW_IDLE_EARN_ENABLED",        # 闲置理财任务
    "CASHFLOW_IDLE_EARN_LIVE",           # false=只 dry 记录；true=真申购 Binance Simple Earn
    "CASHFLOW_IDLE_EARN_ACCOUNT_IDS",    # 逗号分隔 live Binance 账户；空=自动发现
    "CASHFLOW_IDLE_MIN_USDT",            # 超过多少闲置 USDT 才申购（默认 200）
    "CASHFLOW_IDLE_MAX_SUBSCRIBE_USDT",  # 单次申购上限（默认 5000）
    "CASHFLOW_IDLE_RESERVE_USDT",        # 账户保留 USDT（默认 100）
    # ── [v3 方向3 p1-agents-a] SignalReview / Anomaly / Timing 观察模式 Agent ──
    "AGENTS_ENABLED",                    # Agent 定时任务总开关（默认 true；关闭后到期评分器仍挂载）
    "AGENT_LLM_ENABLED",                 # Agent 的 LLM 解释层（默认 false：确定性核心不消耗模型配额）
    "AGENT_GATE_MIN_SCORED",             # 升级到 advise 所需已评分预测数（默认 30）；AGENT_GATE_MIN_SCORED_<AGENT> 可单独覆盖
    "AGENT_GATE_MIN_SCORE",              # 升级所需平均得分（默认 0.55）
    "AGENT_GATE_MAX_BRIER",              # 升级允许的最大 Brier（默认 0.30）
    "AGENT_SIGNAL_REVIEW_DAYS",          # 复盘回看天数（默认 30）
    "AGENT_SIGNAL_REVIEW_MIN_N",         # 出结论所需最少信号数（默认 20）
    "AGENT_SIGNAL_REVIEW_MIN_N_PRED",    # 落 source_edge 预测所需最少信号数（默认 30）
    "AGENT_SIGNAL_REVIEW_WINDOW_H",      # source_edge 预测窗口小时（默认 168）
    "AGENT_SIGNAL_REVIEW_BUCKET_MIN_N",  # 半衰期曲线每桶最少样本（默认 10）
    "AGENT_ANOMALY_LOOKBACK_H",          # 异常检测回看小时（默认 168）
    "AGENT_ANOMALY_REDUCE_SCORE",        # stress 到多少建议 REDUCING（默认 0.55）
    "AGENT_ANOMALY_HALT_SCORE",          # stress 到多少建议 HALTED（默认 0.80）
    "AGENT_ANOMALY_WINDOW_H",            # trading_state 预测窗口小时（默认 24）
    "AGENT_ANOMALY_STRESS_DD_PCT",       # 评分口径：窗口内 BTC 回撤 ≥ 该值视为真有压力（默认 4.0）
    "AGENT_ANOMALY_STALE_H",             # 数据源静默多少小时算陈旧（默认 6）
    "AGENT_ANOMALY_LLM_MIN_STRESS",      # stress 低于该值不调 LLM 归因（默认 0.35；硬触发无视）
    "AGENT_TIMING_WINDOW_H",             # regime 预测窗口小时（默认 168）
    "AGENT_TIMING_HIGH_VOL_PCT",         # BTC 60d 实现波动 ≥ 该值判 high_vol（默认 100）
    "AGENT_TIMING_MIN_UP",               # 一致方向门槛上限（默认 5；8 币实际取 4）
    "AGENT_TIMING_LIQ_FLOOR",            # 7d/90d 均量比低于该值且无方向 → low_liquidity（默认 0.35）
    # ── [v3 方向3 p2-agents-b] EventImpact / ParamSearch / ExecutionQA + 实验卡闭环 ──
    "AGENT_EVENT_IMPACT_MIN_N",          # 事件类型出结论所需最少样本（默认 30）
    "AGENT_EVENT_IMPACT_WINDOW_H",       # event_impact 预测窗口小时（默认 336 = 14 天）
    "AGENT_EVENT_IMPACT_REFRESH",        # true=现算全量事件研究（分钟级）；默认 false 读 event_study 落盘报告
    "AGENT_PARAM_SEARCH_ENABLED",        # ParamSearch 扫描开关（默认 true；扫描只读不下单）
    "AGENT_PARAM_TARGETS",               # 逗号分隔的扫描目标（默认全部 E5 策略）
    "AGENT_PARAM_TRAIN_FRAC",            # 样本外切分比例（默认 0.7：前 70% 训练、后 30% 检验）
    "AGENT_PARAM_MIN_N_TEST",            # 样本外最少样本数，不足不提议（默认 30）
    "AGENT_PARAM_WINDOW_H",              # param_shift 预测窗口小时（默认 336）
    "AGENT_EXEC_QA_LOOKBACK_H",          # 执行质量回看小时（默认 168）
    "AGENT_EXEC_QA_SLIP_WARN_BP",        # 滑点中位数警戒线 bp（默认 8）
    "AGENT_EXEC_QA_REJECT_WARN",         # 拒单率警戒线（默认 0.05）
    "AGENT_EXEC_QA_WINDOW_H",            # exec_quality 预测窗口小时（默认 24）
    "AGENT_EXEC_QA_MIN_ORDERS",          # 出结论所需最少订单数（默认 20）
    "EXPERIMENT_AUTO_START",             # 观察型实验卡自动 proposed→running（默认 true；改配置型永远需人工）
    "EXPERIMENT_MAX_EXTENSIONS",         # 样本不足最多延长几次，超限按无结论结案（默认 3）
    # ── [v3 方向2 p2-oms-exec] 订单状态机 / client_order_id / maker 追价 / 日对账 ──
    "OMS_RECORD_ORDERS",                 # 现有下单路径落 live_orders（默认 true；不改下单方式）
    "OMS_SHADOW",                        # ExecutionAlgo 影子模式：走状态机但不发真单（默认 true）
    "OMS_CLIENT_ID_PREFIX",              # client_order_id 前缀（默认 ha；便于交易所后台辨认）
    "OMS_JOBS_ENABLED",                  # 悬挂扫描 + 日对账任务开关（默认 true）
    "OMS_STUCK_SEC",                     # 悬挂单告警阈值秒（默认 300）
    "OMS_RECONCILE_AUTO_FIX",            # 对账是否自动改写本地状态（默认 false：只报告）
    "OMS_RECONCILE_LOOKBACK_H",          # 对账回看小时（默认 48）
    "OMS_RECONCILE_UNKNOWN_GRACE_SEC",   # submitted/unknown 无交易所证据多久后标 expired（默认 3600）
    "EXEC_ALGO_ENABLED",                 # 接管下单走 maker 追价（默认 false；须显式打开）
    "EXEC_ALGO_CHASE_TIMEOUT_S",         # 单次挂单等待秒（默认 8）
    "EXEC_ALGO_MAX_CHASES",              # 最多追价次数含首次（默认 3）
    "EXEC_ALGO_CHASE_STEP_BP",           # 每次向对手价靠拢步长 bp（默认 1）
    "EXEC_ALGO_POLL_INTERVAL_S",         # 轮询间隔秒（默认 1.5）
    "EXEC_ALGO_FALLBACK",                # 追不到后：market|cancel|leave（默认 market）
    "EXEC_ALGO_POST_ONLY",               # 是否 post-only（默认 true）
    # ── [v3 方向5 p2-arb-infra] 套利 scorecard / 资金划转 / carry 小资金 ──
    "ARB_SCORECARD_DAYS",                # scorecard 回看天数（默认 30）
    "ARB_SCORECARD_MIN_N",               # 小资金晋升门：最少平仓/日志样本（默认 10）
    "ARB_SCORECARD_MIN_ANN",             # 小资金晋升门：最低年化（默认 0.05）
    "FUND_TRANSFER_ENABLED",             # 资金划转服务总开关（默认 false）
    "FUND_TRANSFER_LIVE",                # false=只 dry 记账；true=真调交易所 transfer（默认 false）
    "CASHFLOW_CARRY_SMALL_ENABLED",      # carry 小资金任务（默认 true）
    "CASHFLOW_CARRY_SMALL_LIVE",         # false=研究桶帽名义仍走 Paper；true 才意图 Live（默认 false）
    "CASHFLOW_CARRY_RESEARCH_EQUITY_USD",  # 研究桶权益基准（默认 5000）
    "CASHFLOW_CARRY_RESEARCH_BUCKET_PCT",  # 小资金占研究桶比例（默认 0.05；硬帽 ≤0.20）
    # ── [v3 p3-promotion] 晋升放量 / 分配器 / 尾部 / F4 / 付费决策 ──
    "ALLOCATOR_APPLY",                   # true=把 bucket_weights 写入 runtime_tuning（默认 false）
    "ALLOCATOR_CRED_MIN_N",              # Timing 可信度样本门槛（默认 30）
    "ALLOCATOR_CRED_MIN_SCORE",          # Timing 可信度均分门槛（默认 0.55）
    "ALLOCATOR_RESEARCH_EQUITY_USD",     # 研究桶权益基准（默认 5000）
    "FUNDING_TAIL_ENABLED",              # 尾部 funding 扫描（默认 true）
    "FUNDING_TAIL_LIVE",                 # 尾部收割真下单意图（默认 false）
    "FUNDING_TAIL_ENTER_APR",            # 入场年化阈值（默认 0.50）
    "FUNDING_TAIL_EXIT_APR",             # 出场年化阈值（默认 0.15）
    "FUNDING_TAIL_MIN_STREAK",           # 连续结算窗口数（默认 3）
    "BASIS_ENTRY_MIN_ABS_PCT",           # 基差入场 |%| 门槛（默认 0.15）
    "BASIS_SMALL_ENABLED",               # 未晋级时仍允许 Paper 小名义（默认 true）
    "BASIS_LIVE",                        # 基差 Live（默认 false）
    "BASIS_PAPER_NOTIONAL_USD",          # Paper 默认名义（默认 200）
    "E5_AUTO_PROMOTE",                   # E5 过门自动写入研究桶阶梯（默认 false）
    "E5_RESEARCH_LIVE",                  # E5 研究桶真下单（默认 false）
    "TREND_E1_LIVE_ASTER",               # E1 Aster 小额实盘意图（默认 false；须 F4 过门）
    "TREND_E1_F4_MIN_DAYS",              # F4：最少模拟天数（默认 28）
    "TREND_E1_F4_MAX_DRIFT",             # F4：|drift| 上限（默认 0.02）
    "TREND_E1_F4_MAX_FEE_PCT_WEEK",      # F4：周费用/权益上限（默认 0.01）
    "TREND_E1_F4_SKIP_FEE",              # F4：跳过费用项（默认 false）
    "TREND_E1_F4_HALT_TESTS_OK",         # F4：声明停机单测已绿（默认 false）
    # ── p2-event-strategies：E5 事件影子车道（只入 signal_ledger，无下单路径）──
    "E5_SHADOW_ENABLED",                 # E5 影子车道总开关（默认 true）
    "E5_E5_2_FUNDING_SHOCK_SHADOW_ENABLED",   # 单策略开关：资金费突变
    "E5_E5_3_LIQ_CASCADE_SHADOW_ENABLED",     # 单策略开关：清算级联
    "E5_E5_5_NEWS_HEDGE_SHADOW_ENABLED",      # 单策略开关：新闻避险
    "E5_E5_2_FUNDING_SHOCK_LOOKBACK_H",       # 影子扫描回看小时（默认 24）
    "E5_E5_3_LIQ_CASCADE_LOOKBACK_H",
    "E5_E5_5_NEWS_HEDGE_LOOKBACK_H",
    "E5_FUNDING_Z",                      # E5-2 |Δfunding| z 阈值（默认 3.0）
    "E5_FUNDING_MIN_HISTORY",            # E5-2 滚动窗最少样本数（默认 60 ≈ 20 天）
    "E5_FUNDING_ROLL_WINDOW",            # E5-2 滚动窗长度（默认 60）
    "E5_FUNDING_REQUIRE_OI",             # E5-2 是否要求 OI 同向增确认（默认 true）
    "E5_FUNDING_OI_MIN_PCT",             # E5-2 OI 同向增最低幅度 %（默认 2.0；无 OI 时降置信入账）
    "E5_FUNDING_OI_WINDOW_H",            # E5-2 OI 变化观察窗小时（默认 8）
    "E5_FUNDING_HORIZON_H",              # E5-2 信号时长（默认 4）
    "E5_FUNDING_MIN_ABS_8H",             # E5-2 绝对费率下限，滤 0 附近噪声（默认 0.0002）
    "E5_LIQ_BUCKET_MIN",                 # E5-3 滚动桶宽分钟（默认 30；回退小时源时自动用 60）
    "E5_LIQ_MIN_HISTORY_BUCKETS",        # E5-3 算 P99 所需最少历史桶（默认 336 = 7 天）
    "E5_LIQ_PERCENTILE",                 # E5-3 分位阈值（默认 0.99）
    "E5_LIQ_SIDE_RATIO",                 # E5-3 单边率下限（默认 0.70）
    "E5_LIQ_MIN_NOTIONAL_USD",           # E5-3 绝对金额下限（默认 200 万美元）
    "E5_LIQ_HORIZON_H",                  # E5-3 信号时长（默认 2）
    "E5_LIQ_COOLDOWN_BUCKETS",           # E5-3 同币冷却桶数（默认 4）
    "E5_NEWS_MIN_STRENGTH",              # E5-5 最低新闻强度（量纲 1–5，默认 4）
    "E5_NEWS_MIN_DIRECTION",             # E5-5 最低 |方向|（默认 0.5）
    "E5_NEWS_HEDGE_HOURS",               # E5-5 负面新闻避险窗小时（默认 6）
    "E5_NEWS_POS_HORIZON_H",             # E5-5 正面新闻信号时长（默认 3）
    "E5_NEWS_COOLDOWN_MIN",              # E5-5 同币冷却分钟（默认 60）
    "E5_NEWS_HEDGE_LEV_MULT",            # E5-5 避险窗内杠杆乘数（默认 0.5；Phase 3 才生效）
    "SCALP_SIGNAL_LOG_MIN_SCORE",
    "SCALP_SIZE_PCT",
    "SCALP_MIN_MARGIN_PCT",
    "SCALP_MAX_TRADE_RISK_PCT",
    "SCALP_EXCLUDE_PATTERN",
    "SCALP_META_IN_EV",
    "SCALP_META_EV_BLEND",
    "SCALP_STRICT_VALIDATION",
    "PAIR_SELECTOR_WATCHER_ENABLED",
    "PAIR_SELECTOR_WATCHER_INTERVAL_SEC",
    "PAIR_BINDING_LANE_ENABLED",
    "PAIR_BINDING_LANE_INTERVAL_SEC",
    "SCALP_CIRCUIT_BREAKER_ENABLED",
    "SCALP_CIRCUIT_BREAKER_INTERVAL_SEC",
    "PAIR_AUTO_PROMOTE_MIN_PASS",
    "PAIR_AUTO_PROMOTE_MIN_PF",
    "PAIR_AUTO_PROMOTE_MIN_T",
    "SCALP_STRUCTURE_SL_BUFFER_PCT",
    "SCALP_USE_LLM_CONFIRM",
    "SCALP_VETO_BAND_LOW",
    "SCALP_VETO_FAIL_OPEN",
    "SCALP_VETO_MODE",
    "SCALP_VETO_TIMEOUT_S",
    "SCALP_WICK_DENSITY_BLOCK_THRESHOLD",
    "SCALP_WICK_MANIPULATION_GUARD_ENABLED",
    "SCHEDULER_DISABLED",
    "SECRET_KEY",
    "SHORT_MIN_HOLD_BEFORE_SL_SEC",
    "SHORT_TIER_CONFIDENCE_EXTRA",
    "SHORT_TIER_DISABLED_NATURES",
    "SHORT_TIER_SAME_DIR_COOLDOWN_S",
    "SHORT_TIER_SAME_DIR_COOLDOWN_PAPER_S",
    "SHORT_TIER_SKIP_CONFIDENCE",
    "SIGNAL_FREQUENCY_GUARD_HOURS",
    "SNAPSHOT_DATABASE_URL",
    "SNAPSHOT_FALLBACK_EXCHANGE",
    "SNAPSHOT_KLINE_COUNT",
    "SNAPSHOT_PRIMARY_EXCHANGE",
    "SNAPSHOT_SCHEDULER_INTERVAL",
    "SNAPSHOT_STORE_ENABLED",
    "SQLITE_MAX_OVERFLOW",
    "SQLITE_POOL_SIZE",
    "SQLITE_SOURCE_URL",
    "STRATEGY_GUARD_COOLDOWN_HOURS",
    "TREND_DAILY_OPEN_CAP",
    "STRATEGY_GUARD_MIN_SAMPLES",
    "STRATEGY_GUARD_MIN_WINRATE",
    "STRATEGY_GUARD_WINDOW_HOURS",
    "STRICT_DATA_GATE",
    "SWING_CALIBRATOR_CACHE_TTL_SEC",
    "SWING_CALIBRATOR_ENABLED",
    "SWING_CALIBRATOR_LOOKBACK_DAYS",
    "SWING_CALIBRATOR_MIN_SAMPLES",
    # [M1 2026-09-14] 修复切点（0=不切分）
    "SWING_CALIBRATOR_MIN_TS",
    "SWING_CALIBRATOR_PIVOT",
    "SWING_EV_MIN_PCT",
    "SWING_EV_SL_REALIZATION",
    "SWING_EV_TP_REALIZATION",
    "SWING_LLM_MAX_TOKENS",
    "SWING_MIN_ALIGNMENT",
    "TEST_DATABASE_URL",
    "THESIS_POSTMORTEM_COOLDOWN_SEC",
    "TIER_COORDINATOR_TICK_SEC",
    "TIER_DAILY_LOSS_BUDGET_PCT_LONG",
    "TIER_DAILY_LOSS_BUDGET_PCT_MID",
    "TIER_DAILY_LOSS_BUDGET_PCT_SHORT",
    "TIER_HOLD_EXTENSION_MAX_MULT",
    "TIER_LONG_AI_TICK_SEC",
    "TIER_LONG_ANALYSIS_INTERVAL",
    "TIER_LONG_BUDGET",
    "TIER_LONG_COOLDOWN_SEC",
    "TIER_LONG_MAX_HOLD_SEC",
    "TIER_LONG_MAX_MARGIN",
    "TIER_LONG_MIN_HOLD_EMERGENCY_LOSS_PCT",
    "TIER_LONG_MIN_HOLD_SEC",
    "TIER_MID_AI_TICK_SEC",
    "TIER_MID_ANALYSIS_INTERVAL",
    "TIER_MID_BUDGET",
    "TIER_MID_COOLDOWN_SEC",
    "TIER_MID_MAX_HOLD_SEC",
    "TIER_MID_MAX_MARGIN",
    "TIER_MID_MIN_HOLD_EMERGENCY_LOSS_PCT",
    "TIER_MID_MIN_HOLD_SEC",
    "TIER_MID_SL_PCT",
    "TIER_MID_TP_PCT",
    "TIER_MID_USE_ATR",
    "TIER_SHORT_ANALYSIS_INTERVAL",
    "TIER_SHORT_ATR_SL_MULT",
    "TIER_SHORT_ATR_TP_MULT",
    "TIER_SHORT_BUDGET",
    "TIER_SHORT_COOLDOWN_SEC",
    "TIER_SHORT_MAX_HOLD_SEC",
    "TIER_SHORT_MAX_MARGIN",
    "TIER_SHORT_MAX_SL",
    "TIER_SHORT_MAX_TP",
    "TIER_SHORT_MIN_HOLD_EMERGENCY_LOSS_PCT",
    "TIER_SHORT_MIN_HOLD_SEC",
    "TIER_SHORT_MIN_SL",
    "TIER_SHORT_MIN_TP",
    "TIER_SHORT_SL_PCT",
    "TIER_SHORT_TP_PCT",
    "TIER_SHORT_USE_ATR",
    "TIER_TICK_SCHEDULER_ENABLED",
    "TRACE_ID_ENABLED",
    "TRADE_RISK_LLM_MAX_TOKENS",
    "TRADING_DATA_MODE",
    "TRAINING_AUTO_APPLY_MAJOR",
    "TRAINING_AUTO_LIVE",
    "TRAINING_CORE_SYMBOLS",
    "TRAINING_LIVE_ENV",
    "TRAINING_LIVE_MAX_STRATEGIES",
    "TRAINING_LIVE_PROBE_SIZE_MULT",
    "TRAINING_PHASE_AUTO",
    "TRAINING_PHASE_BLOCK_AUTO_COIN",
    "TREND_CALIBRATOR_CACHE_TTL_SEC",
    "TREND_CALIBRATOR_ENABLED",
    "TREND_CALIBRATOR_LOOKBACK_DAYS",
    "TREND_CALIBRATOR_MIN_SAMPLES",
    # [M1 2026-09-14] 修复切点（0=不切分）
    "TREND_CALIBRATOR_MIN_TS",
    "TREND_CALIBRATOR_PIVOT",
    "TREND_EV_MIN_PCT",
    "TREND_EV_SL_REALIZATION",
    "TREND_EV_TP_REALIZATION",
    "TREND_LLM_MAX_TOKENS",
    "TREND_MAX_OPENS_PER_WEEK",
    "TREND_MIN_ALIGNMENT",
    "TREND_MIN_SCORE_TO_OPEN",
    "TREND_PAPER_SCORE_FLOOR",
    "TREND_REQUIRES_KLINE_DEEP",
    "TREND_TRUST_SHOULD_OPEN_SOFT",
    "TREND_REVIEW_INTERVAL_SEC",
    "TREND_REVIEW_MAX_PER_TICK",
    "UNIFIED_DATA_POOL_KLINE_DERIVATIVES_PREFETCH",
    "UNIFIED_DATA_POOL_READ_SNAPSHOT_STORE",
    "UNIFIED_EXIT_EXECUTOR_ENABLED",
    "UNIVERSE_CORR_LOOKBACK_HOURS",
    "UNIVERSE_KLINE_LOOKBACK_HOURS",
    "UNIVERSE_MAX_PAIRWISE_CORR",
    "UNIVERSE_MAX_SIZE",
    "UNIVERSE_MIN_ADV_USD",
    "UNIVERSE_MIN_HISTORY_DAYS",
    "UNIVERSE_VOL_SWEET_HIGH",
    "UNIVERSE_VOL_SWEET_LOW",
    "USE_UNIFIED_EXECUTOR",
    "V5_DAILY_TRADE_CAP_ENABLED",
    "V5_DECISION_CORE_ENABLED",
    "V5_HIGH_CONF_CONF_RELIEF",
    "V5_HIGH_CONF_MIN_RR",
    "V5_HIGH_CONF_THRESHOLD",
    "V5_MAX_DAILY_TRADES",
    "V5_MAX_DAILY_TRADES_LIVE",
    "V5_MAX_DAILY_TRADES_PAPER",
    "V5_MAX_RUNTIME_MIN_RR",
    "V5_MAX_SYMBOL_TRADES_PER_DAY",
    "V5_MAX_SYMBOL_TRADES_PER_DAY_LIVE",
    "V5_MAX_SYMBOL_TRADES_PER_DAY_PAPER",
    "V5_MAX_TRADE_RISK_PCT",
    "V5_MIN_RISK_REWARD",
    "V5_MIN_TP_PCT",
    "V5_SCALP_MIN_CONFIDENCE",
    "V5_SWING_MIN_CONFIDENCE",
    "V5_SWING_MIN_RR",
    "V5_SCALP_MIN_RR",
    "V5_SCALP_MIN_RR_PAPER",
    "V5_SCALP_MIN_TP_PCT",
    "V5_SCALP_MIN_TP_PCT_PAPER",
    "V5_SWING_MIN_RR_PAPER",
    "V5_TREND_FOLLOW_MIN_CONFIDENCE",
    "V5_TREND_MIN_RR",
    "V5_TREND_MIN_RR_PAPER",
    "WHALE_LLM_MIN_INTERVAL_SEC",
    "WHALE_LLM_MIN_USD",
    # [轮47 2026-09-17] IC-WFO 单币判据阈值（factor_wfo.py 读取）。
    # 注意：SYSTEM_PREFIXES 里的 "WFO_" 只覆盖 find_unknown_flags 之外的另一套校验，
    # 本白名单才是 find_unknown_flags 的判据 —— 故必须在此显式登记。
    "WFO_IC_MAX_DECAY",
    "WFO_IC_MAX_P",
    "WFO_IC_MIN_OOS_IC",
    # [轮48 2026-09-17 目标④] 周期语义对齐（config/cycle_semantics.py + main.py 读取）
    "FACTOR_EVO_INTRADAY_1H_ENABLED",
    "FACTOR_EVO_INTRADAY_PERIODS",
    # [轮49 2026-09-17] 因子评估性能开关（factor_engine/evaluation.py 读取）
    "FACTOR_EVAL_ROLLING_FAST",
    # [轮50 2026-09-17] 因子进化任务的 job_registry 可见性接线（evo_subprocess.py / main.py 读取）
    "FACTOR_EVO_JOB_REGISTRY",
    "WS_DELTA_MODE",
    # [F373 2026-09-18 复查补登记] 本次复查新增/发现但未登记的 flag。
    # 由 `python -m backend.config.env_registry --scan` 的候选清单驱动补全；
    # 未登记 ⇒ 启动期告警，且"设了却没人认识"的静默风险（本模块文件头记录的那类事故）。
    "BACKTEST_FACTOR_ATTR",          # live_pipeline_backtest_engine：回测因子名级归因旁路
    "BACKTEST_FACTOR_ATTR_PATH",     # 同上：归因 JSONL 落盘路径
    "FACTORS_LAB_ALIGN_MIN",         # factors_lab/agent3_engineer：c1·c2 对齐拒收阈值（默认 0.35）
    "MLTO_FACTOR_ANCHOR_PERIOD",     # mlto/quant_layer：因子锚周期覆盖（默认取 TIER_CONFIG）
    "MLTO_FACTOR_ANCHOR_WEIGHT",     # mlto/decision_hub：因子锚权重（默认 0.08）
    "V7_CODEGEN_FULL_POOL",          # evolution_memory_v7：取消 Codegen 候选的 LIMIT 200 窗口
    # 以下三个前缀不在 SYSTEM_PREFIXES 内 ⇒ 登记册此前**不会**对其告警（见报告 §30 的盲区记录）；
    # 显式登记是为了文档化与后续收紧校验时可直接生效。
    "LEARNING_READBACK_ENABLED",     # services/learning_readback：学习→策略读回路总开关（默认 auto）
    "LEARNING_READBACK_CHARS",       # 同上：读回路块字符预算
    "LEARNING_READBACK_DEDUPE_SECONDS",  # 同上：读取留痕去重窗口
    "MLTO_DECAY_PENALTY_ENABLED",    # mlto/quant_layer：因子锚是否服从衰减惩罚（默认关）
})


def _matches_system_prefix(flag: str) -> bool:
    return any(flag.startswith(p) for p in SYSTEM_PREFIXES)


def _is_falsy(val: str) -> bool:
    return val.strip().lower() in ("", "0", "false", "no", "off", "disabled", "disable")


# [2026-09-03 v3 方向1] 按车道参数化的 flag 家族（枚举不完，按模式登记）：
#   EXIT_POLICY_<LANE>_<PARAM>   ExitPolicy 车道覆盖（SL_PCT / TP_PCT / TIME_LIMIT_SEC / TRAILING_* / MIN_ROI / TP_STAGES / ...）
#   PC_<PARAM>_<LANE>            PositionConstruction 车道覆盖（MAX_LEVERAGE / RISK_PER_TRADE_PCT / ...）
KNOWN_FLAG_PATTERNS: tuple[re.Pattern[str], ...] = (
    re.compile(r"^EXIT_POLICY_(SHORT|MID|LONG|RESEARCH|ARB)_[A-Z0-9_]+$"),
    re.compile(r"^PC_[A-Z0-9_]+_(SHORT|MID|LONG|RESEARCH|ARB)$"),
    # p1-agents-a / p2-agents-b：AGENT_MODE_<AGENT>（observe|advise|act）与 AGENT_GATE_*_<AGENT> 按 Agent 覆盖
    re.compile(r"^AGENT_MODE_(SIGNAL_REVIEW|ANOMALY|TIMING|EVENT_IMPACT|PARAM_SEARCH|EXECUTION_QA)$"),
    re.compile(r"^AGENT_GATE_(MIN_SCORED|MIN_SCORE|MAX_BRIER)_"
               r"(SIGNAL_REVIEW|ANOMALY|TIMING|EVENT_IMPACT|PARAM_SEARCH|EXECUTION_QA)$"),
)


def _matches_known_pattern(flag: str) -> bool:
    return any(p.match(flag) for p in KNOWN_FLAG_PATTERNS)


def ensure_env_loaded() -> bool:
    """[§63 修复] 确保 `.env` 已进入 os.environ 后再做校验。

    修复前：本模块的 CLI（`python -m backend.config.env_registry --check`）**不加载 .env**，
    于是它扫描的是一个空荡荡的环境 ⇒ 恒返回「未知系统 flag: 0 / 退出码 0」的**假绿**。
    启动路径（`backend/main.py`）恰好因为 `framework_rollout → settings → load_dotenv`
    的偶然顺序而能看到 `.env`，但这种"碰运气"不该是校验器的前提。
    返回是否成功加载（找不到 .env 时返回 False）。
    """
    global _ENV_LOAD_ATTEMPTED, _ENV_LOADED_OK
    if _ENV_LOAD_ATTEMPTED:
        return _ENV_LOADED_OK
    _ENV_LOAD_ATTEMPTED = True
    try:
        from pathlib import Path

        from dotenv import load_dotenv
        root = Path(__file__).resolve().parents[2]      # backend/config → backend → 仓库根
        env_file = root / ".env"
        if env_file.is_file():
            load_dotenv(str(env_file), override=False)   # 不覆盖真实环境变量
            _ENV_LOADED_OK = True
    except Exception as exc:  # pragma: no cover
        logger.debug("[EnvRegistry] .env 加载失败（结果可能为空）: %s", exc)
    return _ENV_LOADED_OK


def find_unknown_flags(env: dict[str, str] | None = None) -> list[str]:
    """返回当前 env 中"匹配系统前缀但未登记"的 flag 列表。

    [§63] `env` 为 None 时先确保 `.env` 已加载，避免"扫描空环境 ⇒ 假绿"。
    """
    if env is None:
        ensure_env_loaded()
        env = os.environ
    unknown: list[str] = []
    for key in env:
        if not key.isupper():
            continue
        if not _matches_system_prefix(key):
            continue
        if key not in KNOWN_FLAGS and not _matches_known_pattern(key):
            unknown.append(key)
    return sorted(unknown)


def find_silently_disabled_safety_flags(env: dict[str, str] | None = None) -> list[str]:
    """返回被设为 falsy 的安全关键 flag（这些若非有意应告警）。"""
    if env is None:
        ensure_env_loaded()
        env = os.environ
    disabled: list[str] = []
    for flag in SAFETY_CRITICAL_FLAGS:
        if flag in env and _is_falsy(env[flag]):
            disabled.append(flag)
    return sorted(disabled)


def validate_strict(env: dict[str, str] | None = None, *, on_unknown: str | None = None) -> None:
    """
    启动期调用。扫描 env，对未知/静默禁用的 flag 按策略处理。

    on_unknown: 'warn' (默认) | 'error' (硬失败，CI/生产用) | 'silent'。
                未传时读 ENV_STRICT=error 则 error，否则 warn。
    """
    if on_unknown is None:
        on_unknown = "error" if os.environ.get("ENV_STRICT", "").lower() == "error" else "warn"

    unknown = find_unknown_flags(env)
    disabled_safety = find_silently_disabled_safety_flags(env)

    # [轮94 P2-14] 可选的反向体检（默认关闭，见 log_governance_report_if_enabled）
    log_governance_report_if_enabled()

    if disabled_safety:
        logger.warning(
            "[EnvRegistry] ⚠️ 安全关键 flag 被设为关闭（请确认是有意为之）: %s",
            ", ".join(disabled_safety),
        )

    if unknown:
        msg = (
            f"[EnvRegistry] 发现 {len(unknown)} 个匹配系统前缀但未登记的 env-flag（"
            f"疑似拼写错误/遗留/静默禁用）: {', '.join(unknown[:20])}"
            f"{' ...' if len(unknown) > 20 else ''}. "
            f"请登记到 config.env_registry.KNOWN_FLAGS 或修正拼写。"
        )
        if on_unknown == "error":
            logger.error(msg)
            raise SystemExit(f"ENV_STRICT=error: {msg}")
        elif on_unknown == "warn":
            logger.warning(msg)
            # [§63 修复 2026-09-10] 若尚未配置任何 logging handler（启动极早期），
            # `logger.warning` 只会走 lastResort 落到 stderr、**进不了文件日志**——
            # 本模块的目的正是"防止静默失效"，不能自己静默。故此处补一条 stderr 兜底。
            try:
                if not logging.getLogger().handlers:
                    sys.stderr.write(msg + "\n")
                    sys.stderr.flush()
            except Exception:
                pass
        # silent: 不输出


# [轮94 P2-14] 环境变量读取入口的**统一**识别式。
# 缺口来源：原式只认 `os.environ/os.getenv/getenv/getenvbool/getenvint/get_flag/getenv_list`，
# 而本仓还有 `env_int/env_float`（`backend/services/agents/base.py:62-69`、
# `backend/services/strategies/event/base.py:52-61`）以及 `_env_int/_env_bool/_env_float`、
# `os.environ["X"]` 下标式。漏掉它们会让「声明了但没人读」的死键报告里
# 整片 `AGENT_ANOMALY_*` / `AGENT_PARAM_*` 变成**假阳性**（实测 134 条里绝大多数是这种）。
_ENV_GETTER_ALT = (
    r'os\.environ(?:\.get)?'
    r'|os\.getenv'
    r'|[A-Za-z_]*getenv[a-z_]*'
    r'|[A-Za-z_]*env_(?:int|float|str|bool|list)'
    r'|get_flag'
)
_ENV_LITERAL_RE = re.compile(
    r'(?:' + _ENV_GETTER_ALT + r')\(\s*["\']([A-Z_][A-Z0-9_]{3,})["\']'
)
_ENV_SUBSCRIPT_RE = re.compile(
    r'os\.environ\[\s*["\']([A-Z_][A-Z0-9_]{3,})["\']\s*\]'
)


def scan_codebase_for_flags(root: str | None = None) -> set[str]:
    """
    静态扫描 backend/**/*.py，提取所有环境变量读取入口的 flag 名。
    用于周期性补全 KNOWN_FLAGS（不自动写入，输出候选供人工审核）。

    [轮94 P2-14] 入口集合见 `_ENV_GETTER_ALT`（含 `env_int/env_float` 等本仓自建 helper
    与 `os.environ["X"]` 下标式），比原实现覆盖面更广 —— 覆盖面不足会让
    「读但未登记」与「声明但没人读」两个方向的报告同时失真。
    """
    root = root or os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    flags: set[str] = set()
    for dirpath, dirnames, filenames in os.walk(root):
        # skip venv/cache
        dirnames[:] = [d for d in dirnames if d not in {'.venv', '__pycache__', '.git', 'node_modules'}]
        for fn in filenames:
            if not fn.endswith('.py'):
                continue
            try:
                with open(os.path.join(dirpath, fn), encoding='utf-8', errors='ignore') as f:
                    text = f.read()
            except OSError:
                continue
            flags.update(_ENV_LITERAL_RE.findall(text))
            flags.update(_ENV_SUBSCRIPT_RE.findall(text))
    return flags


# ══════════════════════════════════════════════════════════════════════════
# [2026-09-18 轮94 修 P2-14] 反向校验：**代码读但从未登记**的 flag
#
# 缺口（轮66 审计 P2-14）：`find_unknown_flags()` 只扫 `os.environ`，方向是
# 「环境里有、名单里没有」。反方向——「代码读了、但名单里没有、`.env` 里也没有」——
# 它**完全看不见**。而后者才是本项目历史上真正咬人的那一类：
# `V5_DAILY_TRADE_CAP_ENABLED` 当初"配了却不生效"，正是因为读取名与写入名不一致，
# 而没有任何一处地方能把两个方向对上。
#
# 实测（2026-09-18）：代码读取 1671 个名字、`KNOWN_FLAGS` 1639 个，
# 仍有 382 个「代码读但未登记」，其中 379 个连 `.env` 都没声明，
# 里面 31 个是 `*_ENABLED/_DISABLED` 形态的**开关** ——
# 也就是说这些开关在 `.env` 里根本不可发现，只能靠读代码才知道它存在。
#
# 本段提供四个查询 + 一个 CLI（`--audit`），并给这三项数量各钉一条棘轮基线
# （只许降不许升），避免债务继续无声增长。
# ══════════════════════════════════════════════════════════════════════════

# getter 调用的实参片段（用于识别 f-string / 拼接这类**动态**读取）
_DYNAMIC_ARG_RE = re.compile(
    r'(?:' + _ENV_GETTER_ALT + r')\(\s*(?P<arg>[^)\n]{0,240})'
)
# 大写片段（含前后下划线），用于把 `f"SCALP_{p}_ENABLED"` 拆成前缀 `SCALP_` / 后缀 `_ENABLED`
_FRAGMENT_RE = re.compile(r'[A-Z0-9_]{5,}')

# 棘轮基线：2026-09-18 实测值。只允许下降；上升即视为新的治理债，必须显式解释。
ENV_READ_UNREGISTERED_BASELINE = 281
ENV_UNDECLARED_SWITCH_BASELINE = 18

_DECLARED_CACHE: dict[str, dict[str, str]] = {}

# 开关型 flag 的后缀。**运行时拼接**而非写成完整字面量：`audit_config_effective` 的
# "后缀拼接读取"启发式会把「含 `_XXX` 引号字面量 + 含拼接式 getter 调用」的文件里
# 所有 `*_XXX` 键判为"动态可读"，写死字面量会把全仓 `*_ENABLED` 整类豁免出死键清单。
_SWITCH_SUFFIXES: tuple[str, ...] = ("_" + "ENABLED", "_" + "DISABLED")


def scan_codebase_for_dynamic_fragments(root: str | None = None) -> set[str]:
    """提取**动态读取**的 env 名前缀/后缀片段（如 `f"AGENT_ANOMALY_{k}"` → `AGENT_ANOMALY_`）。

    为什么需要：`.env` 里 `AGENT_ANOMALY_*` / `SCALP_*` 这类键在代码里是拼接出来的，
    纯字面量扫描看不到它们，于是「声明了但没人读」的死键报告会全是假阳性。
    """
    root = root or os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    frags: set[str] = set()
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in {'.venv', '__pycache__', '.git', 'node_modules'}]
        for fn in filenames:
            if not fn.endswith('.py'):
                continue
            try:
                with open(os.path.join(dirpath, fn), encoding='utf-8', errors='ignore') as f:
                    text = f.read()
            except OSError:
                continue
            for m in _DYNAMIC_ARG_RE.finditer(text):
                arg = m.group('arg')
                # 纯字面量实参不需要片段（已有精确名字）
                if '{' not in arg and '+' not in arg:
                    continue
                for raw in _FRAGMENT_RE.findall(arg):
                    if raw.startswith('_') or raw.endswith('_'):
                        frags.add(raw)
    return frags


def _is_dynamic_read(key: str, fragments: set[str] | None) -> bool:
    """该键是否可能被 `f"PREFIX_{x}"` / `"A" + x` 这类动态读取命中。

    [轮94 校准] 只有**核心含内部下划线**的片段才算有效线索（如 `AGENT_ANOMALY_`、
    `KLINE_RETENTION_DAYS_`、`EXIT_AGENT_MAX_HOLD_SEC_`）。理由：像 `_ENABLED`、
    `_PAPER` 这种"通用词缀"会把**所有** `*_ENABLED` / `*_PAPER` 名字一次性豁免掉 ——
    实测那会让「未声明的开关」从 18 个直接变 0，正好把本函数要报出来的东西全部抹掉
    （P2-14 关心的就是这批开关）。宁可留下几条拼接头噪音，也不能让整类信号消失。
    """
    for frag in (fragments or set()):
        core = frag.strip('_')
        if len(core) < 6 or '_' not in core:
            continue
        if key.startswith(frag) or key.endswith(frag):
            return True
    return False


def read_declared_env_keys(root: str | None = None) -> dict[str, str]:
    """读取 `.env` / `.env.example` 里声明的键 → {键: 来源文件}（带进程内缓存）。"""
    root = root or os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    if root in _DECLARED_CACHE:
        return _DECLARED_CACHE[root]
    declared: dict[str, str] = {}
    for name in ('.env', '.env.example'):
        path = os.path.join(root, name)
        if not os.path.isfile(path):
            continue
        try:
            with open(path, encoding='utf-8', errors='ignore') as f:
                for line in f:
                    line = line.strip()
                    if not line or line.startswith('#'):
                        continue
                    m = re.match(r'^(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=', line)
                    if m:
                        declared.setdefault(m.group(1), name)
        except OSError:
            continue
    _DECLARED_CACHE[root] = declared
    return declared


def find_read_but_unregistered_flags(root: str | None = None) -> list[str]:
    """**代码读、但 `KNOWN_FLAGS` 里没有**的 flag（匹配系统前缀、且不匹配已知模式）。

    这是 `find_unknown_flags()` 的镜像方向，也是本模块此前唯一的盲区。

    已排除两类假阳性：
      · 动态拼接留下的前缀片段（形如「getter 的实参用 `+` 拼接一个变量」时，字面量
        扫描会把那个前缀当成一个真实名字，例如 `EXIT_AGENT_MAX_HOLD_SEC_`）；
      · 匹配 `KNOWN_FLAG_PATTERNS` 的车道参数化族。

    注：本 docstring 刻意不写出「拼接式 getter 调用」的**完整源码形状** ——
    `backend/scripts/audit_config_effective.py` 的"后缀拼接读取"启发式是按**行文本**
    识别的（`RE_COMPOSED_GETENV` 找拼接式调用、`RE_SUFFIX_LITERAL` 收同文件里的
    `_XXX` 字面量）。在注释里写出那种形状，会被它当成真实读取点，
    从而把全仓 `*_ENABLED` 键整类豁免出死键清单（实测会把
    `test_env_registry_visibility_20260910` 顶红）。
    """
    found = scan_codebase_for_flags(root)
    fragments = scan_codebase_for_dynamic_fragments(root)
    return sorted(
        f for f in found
        if _matches_system_prefix(f)
        and f not in KNOWN_FLAGS
        and not _matches_known_pattern(f)
        and not _is_dynamic_read(f, fragments)
    )


def find_undeclared_switch_flags(root: str | None = None) -> list[str]:
    """「代码读 + `.env`/`.env.example` 都没声明 + 开关形态（见 `_SWITCH_SUFFIXES`）」的开关。

    这些开关在配置文件里**不可发现**：运维只能读代码才知道它存在，
    于是"默认关闭"与"忘了打开"在 `.env` 里长得一模一样。
    """
    declared = read_declared_env_keys(root)
    return sorted(
        f for f in find_read_but_unregistered_flags(root)
        if f not in declared and f.endswith(_SWITCH_SUFFIXES)
    )


def find_declared_but_unread_keys(root: str | None = None) -> list[str]:
    """**已废弃的重复实现 —— 请勿使用**，死键方向的真源是既有工具。

    [轮94 P2-14 决策留痕] 本函数曾实现「`.env` 声明了但没人读」的近似检测。落地时发现
    仓库**已有**更完整、且带"白名单 + 原因分类 + 契约测试"的权威实现：

        backend/scripts/audit_config_effective.py  →  findings["env_truly_dead"]
        backend/tests/unit/test_config_dead_keys_20260910.py  →  DEAD_ALLOWLIST 门禁

    那份实现还额外识别「动态前缀读取」与「后缀拼接读取」
    （`env_dynamic_prefix_read` / `env_suffix_composed_read`），并且每一项死键都必须
    在 `DEAD_ALLOWLIST` 里写明原因分类，否则测试变红 —— 这正是 §54 踩过
    「动态读取被误判成死键」之后建立的机制。

    再保留一份"近似版"死键清单，就会重演本项目最贵的那类错误：
    **同一件事两套口径、互相打架**（轮63 的 7 套周期词表就是前车之鉴）。
    故此处不再产出清单，只保留本说明与调用入口，明确指向真源。
    """
    return []


def env_governance_report(root: str | None = None) -> dict:
    """环境变量治理体检（供 CLI `--audit` 与回归测试使用）。

    只覆盖本模块**独有**的那个方向：**代码读取入口覆盖面的反向缺口**
    （「代码读、但既没登记也没在 `.env` 声明」）。
    「`.env` 声明但没人读」的死键方向不在此处重复实现，见
    `find_declared_but_unread_keys()` 的说明。
    """
    declared = read_declared_env_keys(root)
    found = scan_codebase_for_flags(root)
    return {
        "code_read": len(found),
        "registered": len(KNOWN_FLAGS),
        "declared": len(declared),
        "read_but_unregistered": find_read_but_unregistered_flags(root),
        "undeclared_switches": find_undeclared_switch_flags(root),
        "baseline": {
            "read_but_unregistered": ENV_READ_UNREGISTERED_BASELINE,
            "undeclared_switches": ENV_UNDECLARED_SWITCH_BASELINE,
        },
    }


def log_governance_report_if_enabled(root: str | None = None) -> None:
    """启动期可选地把治理体检的**计数**写进日志（默认关闭，扫盘约 1.2s）。

    开关：`ENV_GOVERNANCE_REPORT=true`。默认关闭的理由：`validate_strict()` 在启动
    最早期被调用，为了一条日志付出一次全仓静态扫描不划算；需要时（排查"某个开关
    是不是根本没接线"）打开即可。
    """
    if os.environ.get("ENV_GOVERNANCE_REPORT", "").strip().lower() not in ("1", "true", "yes", "on"):
        return
    try:
        rep = env_governance_report(root)
    except Exception as exc:  # pragma: no cover
        logger.debug("[EnvRegistry] 治理体检失败: %s", exc)
        return
    logger.info(
        "[EnvRegistry] 环境变量治理: 代码读 %s / 已登记 %s / .env 声明 %s；"
        "读但未登记 %s（基线 %s）；其中未声明的开关 %s（基线 %s）",
        rep["code_read"], rep["registered"], rep["declared"],
        len(rep["read_but_unregistered"]), rep["baseline"]["read_but_unregistered"],
        len(rep["undeclared_switches"]), rep["baseline"]["undeclared_switches"],
    )
    over = []
    for key, label in (
        ("read_but_unregistered", "读但未登记"),
        ("undeclared_switches", "未声明的开关"),
    ):
        cur, base = len(rep[key]), rep["baseline"][key]
        if cur > base:
            over.append(f"{label} {cur}>{base}")
    if over:
        logger.warning(
            "[EnvRegistry] ⚠️ 环境变量治理债超出基线: %s（新增未登记项示例: %s）",
            "; ".join(over),
            ", ".join(sorted(set(rep["read_but_unregistered"]))[:10]),
        )


def _cli() -> int:
    """`python -m backend.config.env_registry --scan | --check | --audit`。"""
    if '--audit' in sys.argv:
        rep = env_governance_report()
        print("=== 环境变量治理体检（P2-14）===")
        print(f"代码读取        : {rep['code_read']}")
        print(f"KNOWN_FLAGS     : {rep['registered']}")
        print(f".env/.env.example 声明: {rep['declared']}")
        for key, title, hint in (
            ("read_but_unregistered", "代码读但未登记", "补登 KNOWN_FLAGS 或修正拼写"),
            ("undeclared_switches", "未声明的开关（.env 里不可发现）", "在 .env 里显式声明并注明默认值"),
        ):
            items = rep[key]
            base = rep["baseline"][key]
            flag = "  ⚠️ 超基线" if len(items) > base else ""
            print(f"\n--- {title}: {len(items)}（基线 {base}）{flag} — {hint} ---")
            for it in items[:40]:
                print(f"    {it}")
            if len(items) > 40:
                print(f"    ... 其余 {len(items) - 40} 项")
        print(
            "\n# 「.env 声明但没人读」的死键方向不在此重复实现（单一真源）："
            "\n#   python -m backend.scripts.audit_config_effective"
            "\n#   门禁见 backend/tests/unit/test_config_dead_keys_20260910.py 的 DEAD_ALLOWLIST"
        )
        return 0

    if '--scan' in sys.argv:
        found = scan_codebase_for_flags()
        registered = set(KNOWN_FLAGS)
        missing = sorted(found - registered)
        print(f"# 代码中引用但未登记的 env-flag（候选补全到 KNOWN_FLAGS）：{len(missing)}")
        for f in missing:
            print(f"    \"{f}\",")
        print(f"\n# 已登记：{len(registered)}，代码引用：{len(found)}，待审核：{len(missing)}")
        return 0
    if '--check' in sys.argv:
        unknown = find_unknown_flags()
        disabled = find_silently_disabled_safety_flags()
        print(f"未知系统 flag: {len(unknown)}")
        for f in unknown:
            print(f"  ? {f} = {os.environ.get(f)}")
        print(f"被关闭的安全 flag: {len(disabled)}")
        for f in disabled:
            print(f"  ⚠ {f}")
        # [轮94 P2-14] 顺带报出反向缺口（不参与退出码，避免打断既有 CI 契约）
        try:
            print(f"代码读但未登记: {len(find_read_but_unregistered_flags())}（详见 --audit）")
        except Exception:
            pass
        return 0 if not unknown else 1
    print("用法: python -m backend.config.env_registry --scan | --check | --audit")
    return 0


if __name__ == "__main__":
    sys.exit(_cli())
