"""Assemble A–G full_auto modules from extracted bodies."""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FA = ROOT / "backend/services/full_auto"


def dedent(body: str) -> str:
    out = []
    for line in body.splitlines():
        if line.startswith("        "):
            out.append("    " + line[8:])
        else:
            out.append(line)
    return "\n".join(out)


def load(method: str) -> str:
    name = f"_{method}_body.tmp"
    path = FA / name
    if not path.exists():
        raise SystemExit(f"missing {path}")
    return dedent(path.read_text(encoding="utf-8"))


def write(name: str, parts: list[str]) -> None:
    text = "\n".join(parts) + "\n"
    (FA / name).write_text(text, encoding="utf-8")
    print(name, len(text.splitlines()))


# ── A. paper_session_helpers ─────────────────────────────────────────
write(
    "paper_session_helpers.py",
    [
        '"""模拟盘会话辅助 — 从 monolith 迁出（整改#8 Phase2）。"""',
        "from __future__ import annotations",
        "",
        "import logging",
        "from dataclasses import dataclass, field",
        "from typing import Any, Callable, Dict, List, Optional",
        "",
        "from sqlalchemy.orm import Session",
        "",
        "logger = logging.getLogger(__name__)",
        "",
        "",
        "@dataclass",
        "class PaperSessionHost:",
        "    defensive_entered_at: Dict[str, float] = field(default_factory=dict)",
        "    recovery_until: Dict[str, float] = field(default_factory=dict)",
        "    symbol_frozen_set: Dict[str, set] = field(default_factory=dict)",
        "    strat_pause_meta: Dict[Any, Dict[str, Any]] = field(default_factory=dict)",
        "",
        "    paper_loss_locks_disabled: Callable = field(repr=False, default=lambda *a, **k: False)",
        "    clear_strategy_pause_meta: Callable = field(repr=False, default=lambda *a, **k: None)",
        "    get_trading_account_id: Callable = field(repr=False, default=lambda *a, **k: 0)",
        "    invalidate_session_status_cache: Callable = field(repr=False, default=lambda *a, **k: None)",
        "    should_log_pause_event: Callable = field(repr=False, default=lambda *a, **k: True)",
        "    append_event: Callable = field(repr=False, default=lambda *a, **k: None)",
        "    record_strategy_pause: Callable = field(repr=False, default=lambda *a, **k: None)",
        "    safe_commit: Callable = field(repr=False, default=lambda *a, **k: True)",
        "    utc_iso: Callable = field(repr=False, default=lambda *a, **k: None)",
        "",
        "",
        "def build_paper_session_host(svc) -> PaperSessionHost:",
        "    return PaperSessionHost(",
        "        defensive_entered_at=svc._defensive_entered_at,",
        "        recovery_until=svc._recovery_until,",
        '        symbol_frozen_set=getattr(svc, "_symbol_frozen_set", None) or {},',
        '        strat_pause_meta=getattr(svc, "_strat_pause_meta", None) or {},',
        "        paper_loss_locks_disabled=svc._paper_loss_locks_disabled,",
        "        clear_strategy_pause_meta=svc._clear_strategy_pause_meta,",
        "        get_trading_account_id=svc._get_trading_account_id,",
        "        invalidate_session_status_cache=svc._invalidate_session_status_cache,",
        "        should_log_pause_event=svc._should_log_pause_event,",
        "        append_event=svc._append_event,",
        "        record_strategy_pause=svc._record_strategy_pause,",
        "        safe_commit=svc._safe_commit,",
        "        utc_iso=svc._utc_iso,",
        "    )",
        "",
        "",
        "def paper_auto_unlock_session(db: Session, session, host: PaperSessionHost) -> bool:",
        load("_paper_auto_unlock_session"),
        "",
        "def cap_paper_active_strategies(",
        "    db: Session, session, active_ids: list, host: PaperSessionHost,",
        "    *, max_per_symbol: Optional[int] = None,",
        ") -> bool:",
        load("_cap_paper_active_strategies"),
        "",
        "def get_trade_history(db, session, host: PaperSessionHost) -> list:",
        load("_get_trade_history"),
        "",
        "def cleanup_duplicate_strategies(db, host: PaperSessionHost):",
        load("_cleanup_duplicate_strategies"),
    ],
)

# ── B. orch_background ───────────────────────────────────────────────
write(
    "orch_background.py",
    [
        '"""编排器后台 / 缓存清理 / 调度桩 — 从 monolith 迁出（整改#8 Phase2）。"""',
        "from __future__ import annotations",
        "",
        "import logging",
        "import threading",
        "import time",
        "from dataclasses import dataclass, field",
        "from typing import Any, Callable, Dict, List, Optional",
        "",
        "logger = logging.getLogger(__name__)",
        "",
        "",
        "@dataclass",
        "class OrchBackgroundHost:",
        "    last_cache_purge: float = 0.0",
        "    last_close_time: Dict[str, float] = field(default_factory=dict)",
        "    last_reduce_time: Dict[str, Any] = field(default_factory=dict)",
        "    master_strat_cache: Dict[str, Any] = field(default_factory=dict)",
        "    partial_close_tracker: Dict[str, dict] = field(default_factory=dict)",
        "    market_scan_cache: Dict[str, dict] = field(default_factory=dict)",
        "    market_scan_cache_ts: float = 0.0",
        "    strategy_creation_ts: Dict[str, float] = field(default_factory=dict)",
        "    health_status: Dict[str, Any] = field(default_factory=dict)",
        "    current_ai_tiers: Optional[List[str]] = None",
        "    last_orch_decisions: Dict[str, Any] = field(default_factory=dict)",
        "    last_orch_decisions_ts: float = 0.0",
        "    orch_bg_thread: Any = None",
        "    orch_bg_session_id: Optional[str] = None",
        "    orch_bg_symbols: List[str] = field(default_factory=list)",
        "    orch_bg_running: bool = False",
        "    last_unified_snapshot: Any = None",
        "",
        "    ensure_fresh_orch_decisions: Callable = field(repr=False, default=lambda *a, **k: {})",
        "    tier_confidence_pct: Callable = field(repr=False, default=lambda *a, **k: 50)",
        "    resolve_session_trade_symbols: Callable = field(repr=False, default=lambda *a, **k: [])",
        '    active_exchange: Callable = field(repr=False, default=lambda: "binance")',
        "    orch_payload_from_decision: Callable = field(repr=False, default=lambda *a, **k: {})",
        "",
        "",
        "def build_orch_background_host(svc) -> OrchBackgroundHost:",
        "    return OrchBackgroundHost(",
        '        last_cache_purge=float(getattr(svc, "_last_cache_purge", 0) or 0),',
        '        last_close_time=getattr(svc, "_last_close_time", None) or {},',
        '        last_reduce_time=getattr(svc, "_last_reduce_time", None) or {},',
        '        master_strat_cache=getattr(svc, "_master_strat_cache", None) or {},',
        '        partial_close_tracker=getattr(svc, "_partial_close_tracker", None) or {},',
        '        market_scan_cache=getattr(svc, "_market_scan_cache", None) or {},',
        '        market_scan_cache_ts=float(getattr(svc, "_market_scan_cache_ts", 0) or 0),',
        '        strategy_creation_ts=getattr(svc, "_strategy_creation_ts", None) or {},',
        '        health_status=getattr(svc, "_health_status", None) or {},',
        '        current_ai_tiers=getattr(svc, "_current_ai_tiers", None),',
        '        last_orch_decisions=getattr(svc, "_last_orch_decisions", None) or {},',
        '        last_orch_decisions_ts=float(getattr(svc, "_last_orch_decisions_ts", 0) or 0),',
        '        orch_bg_thread=getattr(svc, "_orch_bg_thread", None),',
        '        orch_bg_session_id=getattr(svc, "_orch_bg_session_id", None),',
        '        orch_bg_symbols=list(getattr(svc, "_orch_bg_symbols", None) or []),',
        '        orch_bg_running=bool(getattr(svc, "_orch_bg_running", False)),',
        '        last_unified_snapshot=getattr(svc, "_last_unified_snapshot", None),',
        "        ensure_fresh_orch_decisions=svc._ensure_fresh_orch_decisions,",
        "        tier_confidence_pct=svc._tier_confidence_pct,",
        "        resolve_session_trade_symbols=svc._resolve_session_trade_symbols,",
        "        active_exchange=svc._active_exchange,",
        "        orch_payload_from_decision=svc._orch_payload_from_decision,",
        "    )",
        "",
        "",
        "def build_fast_stability_result(",
        "    symbols,",
        '    *,',
        '    trigger: str = "timeout",',
        "    timeout_s: Optional[float] = None,",
        ") -> dict:",
        load("_build_fast_stability_result"),
        "",
        "def purge_stale_caches(host: OrchBackgroundHost) -> None:",
        load("_purge_stale_caches"),
        "",
        "def inject_orch_scheduled_stubs(",
        "    decisions: list,",
        "    market_summary: dict,",
        "    host: OrchBackgroundHost,",
        "    session=None,",
        ") -> list:",
        load("_inject_orch_scheduled_stubs"),
        "",
        "def ensure_orchestrator_bg_running(",
        "    session_id: str, symbols: list, host: OrchBackgroundHost,",
        ") -> None:",
        load("_ensure_orchestrator_bg_running"),
    ],
)

# ── C. decision_sizing ───────────────────────────────────────────────
write(
    "decision_sizing.py",
    [
        '"""决策仓位 / 杠杆 / 置信度 — 从 monolith 迁出（整改#8 Phase2）。"""',
        "from __future__ import annotations",
        "",
        "import logging",
        "from dataclasses import dataclass, field",
        "from typing import Any, Callable, Dict, Optional, Set",
        "",
        "from sqlalchemy.orm import Session",
        "",
        "logger = logging.getLogger(__name__)",
        "",
        "",
        "@dataclass",
        "class DecisionSizingHost:",
        "    last_orch_decisions: Dict[str, Any] = field(default_factory=dict)",
        "    pre_screen_passed: Set[str] = field(default_factory=set)",
        "    extract_ai_position_pct: Callable = field(repr=False, default=lambda *a, **k: None)",
        "",
        "",
        "def build_decision_sizing_host(svc) -> DecisionSizingHost:",
        "    return DecisionSizingHost(",
        '        last_orch_decisions=getattr(svc, "_last_orch_decisions", None) or {},',
        '        pre_screen_passed=getattr(svc, "_pre_screen_passed", None) or set(),',
        "        extract_ai_position_pct=svc._extract_ai_position_pct,",
        "    )",
        "",
        "",
        "def ai_dynamic_position_pct(",
        "    confidence: int, volatility: float,",
        "    open_position_count: int,",
        '    tier: str = "mid",',
        "    tier_budget_pct: float = 0.0,",
        ") -> float:",
        load("_ai_dynamic_position_pct"),
        "",
        "def apply_tdi_position_advice(",
        "    symbol: str,",
        "    base_pct: float,",
        "    confidence: int,",
        "    volatility: float,",
        "    open_position_count: int,",
        '    tier: str = "mid",',
        "    tier_budget_pct: float = 0.0,",
        "    equity: float = 0.0,",
        '    regime: str = "ranging",',
        '    base_direction: str = "hold",',
        "):",
        load("_apply_tdi_position_advice"),
        "",
        "def resolve_alignment_scale(sym: str, host: DecisionSizingHost) -> float:",
        load("_resolve_alignment_scale"),
        "",
        "def resolve_decision_leverage(",
        "    dec: dict,",
        "    sym: str,",
        "    tier: str,",
        "    mkt: dict,",
        "    db: Session,",
        "    account_id: int,",
        '    trade_nature: str = "",',
        "    market_summary: dict = None,",
        ") -> tuple:",
        load("_resolve_decision_leverage"),
        "",
        "def resolve_decision_position_pct(",
        "    dec: dict,",
        "    confidence: int,",
        "    vol_value: float,",
        "    open_position_count: int,",
        "    tier: str,",
        "    tier_budget_pct: float,",
        "    total_equity: float,",
        "    market_regime: str,",
        "    sym: str,",
        "    action: str,",
        "    host: DecisionSizingHost,",
        ") -> tuple:",
        load("_resolve_decision_position_pct"),
        "",
        "def calibrate_confidence(",
        "    raw_conf: int, action: str, symbol: str,",
        "    analyst_reports: dict, market_summary: dict,",
        "    host: DecisionSizingHost,",
        ") -> int:",
        load("_calibrate_confidence"),
    ],
)

# ── D. tp_sl_gates ───────────────────────────────────────────────────
write(
    "tp_sl_gates.py",
    [
        '"""TP/SL 校验与因子否决 — 从 monolith 迁出（整改#8 Phase2）。"""',
        "from __future__ import annotations",
        "",
        "import logging",
        "import time",
        "from dataclasses import dataclass, field",
        "from typing import Any, Dict, Optional",
        "",
        "from sqlalchemy.orm import Session",
        "",
        "logger = logging.getLogger(__name__)",
        "",
        "",
        "@dataclass",
        "class TpSlGatesHost:",
        "    v3_factor_cache: Dict[str, dict] = field(default_factory=dict)",
        "",
        "",
        "def build_tp_sl_gates_host(svc) -> TpSlGatesHost:",
        "    return TpSlGatesHost(",
        '        v3_factor_cache=getattr(svc, "_v3_factor_cache", None) or {},',
        "    )",
        "",
        "",
        "def factor_veto_check(",
        '    db: Session, sym: str, action: str, host: TpSlGatesHost, mode: str = "paper",',
        ") -> Optional[str]:",
        load("_factor_veto_check"),
        "",
        "def compute_dynamic_min_sl(",
        "    symbol: str, trade_nature: str, entry_price: float,",
        "    fallback_pct: float = 0.025,",
        ") -> float:",
        load("_compute_dynamic_min_sl"),
        "",
        "def validate_tp_sl_by_nature(",
        "    trade_nature: str, side: str, entry_price: float,",
        '    tp_price, sl_price, symbol: str = "",',
        ") -> tuple:",
        load("_validate_tp_sl_by_nature"),
    ],
)

# ── E. live_trading ──────────────────────────────────────────────────
write(
    "live_trading.py",
    [
        '"""实盘宪法风控与下单 — 从 monolith 迁出（整改#8 Phase2）。"""',
        "from __future__ import annotations",
        "",
        "import logging",
        "import time",
        "from dataclasses import dataclass, field",
        "from typing import Any, Callable, Dict",
        "",
        "from sqlalchemy.orm import Session",
        "",
        "logger = logging.getLogger(__name__)",
        "",
        "",
        "@dataclass",
        "class LiveTradingHost:",
        "    defensive_entered_at: Dict[str, float] = field(default_factory=dict)",
        "",
        "    is_live_trading_session: Callable = field(repr=False, default=lambda *a, **k: False)",
        "    is_unified_executor_on: Callable = field(repr=False, default=lambda: False)",
        "    should_switch_mode: Callable = field(repr=False, default=lambda *a, **k: True)",
        "    append_event: Callable = field(repr=False, default=lambda *a, **k: None)",
        "    invalidate_session_status_cache: Callable = field(repr=False, default=lambda *a, **k: None)",
        "    should_log_pause_event: Callable = field(repr=False, default=lambda *a, **k: True)",
        "",
        "",
        "def build_live_trading_host(svc) -> LiveTradingHost:",
        "    return LiveTradingHost(",
        "        defensive_entered_at=svc._defensive_entered_at,",
        "        is_live_trading_session=svc._is_live_trading_session,",
        "        is_unified_executor_on=svc._is_unified_executor_on,",
        "        should_switch_mode=svc._should_switch_mode,",
        "        append_event=svc._append_event,",
        "        invalidate_session_status_cache=svc._invalidate_session_status_cache,",
        "        should_log_pause_event=svc._should_log_pause_event,",
        "    )",
        "",
        "",
        "def live_constitutional_enabled(session, host: LiveTradingHost) -> bool:",
        load("_live_constitutional_enabled"),
        "",
        "def fetch_live_account_snapshot(db: Session, account_id: int) -> dict:",
        load("_fetch_live_account_snapshot"),
        "",
        "def live_constitutional_pre_trade_check(",
        "    db: Session, session, strat, decision: dict, host: LiveTradingHost,",
        ") -> tuple:",
        load("_live_constitutional_pre_trade_check"),
        "",
        "def check_live_constitutional_session_risk(",
        "    db: Session, session, host: LiveTradingHost,",
        ") -> None:",
        load("_check_live_constitutional_session_risk"),
        "",
        "def execute_live_trade(",
        "    db: Session, session, strat, decision: dict, host: LiveTradingHost,",
        ") -> None:",
        load("_execute_live_trade"),
    ],
)

# ── F. midlong_helpers ───────────────────────────────────────────────
write(
    "midlong_helpers.py",
    [
        '"""中长线独立 Agent 辅助 — 从 monolith 迁出（整改#8 Phase2）。"""',
        "from __future__ import annotations",
        "",
        "import json",
        "import logging",
        "from dataclasses import dataclass, field",
        "from typing import Callable, List, Optional",
        "",
        "from sqlalchemy.orm import Session",
        "",
        "logger = logging.getLogger(__name__)",
        "",
        "",
        "@dataclass",
        "class MidlongHelpersHost:",
        "    get_trading_account_id: Callable = field(repr=False, default=lambda *a, **k: 0)",
        "    append_event: Callable = field(repr=False, default=lambda *a, **k: None)",
        "    evaluate_and_execute_proposal: Callable = field(repr=False, default=lambda *a, **k: False)",
        "",
        "",
        "def build_midlong_helpers_host(svc) -> MidlongHelpersHost:",
        "    return MidlongHelpersHost(",
        "        get_trading_account_id=svc._get_trading_account_id,",
        "        append_event=svc._append_event,",
        "        evaluate_and_execute_proposal=svc._evaluate_and_execute_proposal,",
        "    )",
        "",
        "",
        "def resolve_independent_strategy(",
        "    db: Session, session, sym_u: str, tier: str, host: MidlongHelpersHost,",
        "):",
        load("_resolve_independent_strategy"),
        "",
        "def try_execute_independent_agent_open(",
        "    *,",
        "    db: Session,",
        "    session,",
        "    sym: str,",
        "    tier: str,",
        "    action: str,",
        "    confidence: int,",
        "    sl_pct: float = 0.0,",
        "    tp_pct: float = 0.0,",
        "    trade_nature: str,",
        "    market_summary: dict,",
        '    session_mode: str = "running",',
        "    host: MidlongHelpersHost,",
        ") -> bool:",
        load("_try_execute_independent_agent_open"),
        "",
        "def record_midlong_factor_snapshots(",
        "    *,",
        "    db,",
        "    account_id: int,",
        "    trade_id: int,",
        "    symbol: str,",
        "    side: str,",
        "    market_data: dict,",
        ") -> None:",
        load("_record_midlong_factor_snapshots"),
        "",
        "def persist_independent_scan_log(",
        "    *,",
        "    account_id: Optional[int],",
        "    symbol: str,",
        "    tier: str,",
        "    trade_nature: str,",
        "    action: str,",
        "    confidence: float,",
        "    reasoning: str,",
        "    agent_source: str,",
        "    cited_fact_ids: Optional[List[str]] = None,",
        "    evidence_audit: Optional[dict] = None,",
        "    market_summary: Optional[dict] = None,",
        ") -> None:",
        load("_persist_independent_scan_log"),
        "",
        "def inject_midlong_indicators(",
        "    market_summary: dict, symbol: str, include_weekly: bool = False,",
        ") -> None:",
        load("_inject_midlong_indicators"),
    ],
)

# ── G. data_health ───────────────────────────────────────────────────
write(
    "data_health.py",
    [
        '"""数据健康检查 — 从 monolith 迁出（整改#8 Phase2）。"""',
        "from __future__ import annotations",
        "",
        "import logging",
        "from dataclasses import dataclass, field",
        "from typing import Any, Callable, Dict, List, Set",
        "",
        "logger = logging.getLogger(__name__)",
        "",
        "",
        "@dataclass",
        "class DataHealthHost:",
        "    symbol_frozen_set: Dict[str, set] = field(default_factory=dict)",
        "    health_status: Dict[str, Any] = field(default_factory=dict)",
        "",
        "    freeze_symbol_strategies: Callable = field(repr=False, default=lambda *a, **k: None)",
        "    append_event: Callable = field(repr=False, default=lambda *a, **k: None)",
        "",
        "",
        "def build_data_health_host(svc) -> DataHealthHost:",
        "    return DataHealthHost(",
        '        symbol_frozen_set=getattr(svc, "_symbol_frozen_set", None) or {},',
        '        health_status=getattr(svc, "_health_status", None) or {},',
        "        freeze_symbol_strategies=svc._freeze_symbol_strategies,",
        "        append_event=svc._append_event,",
        "    )",
        "",
        "",
        "def check_data_health(",
        "    session, market_summary: Dict[str, Any],",
        "    symbols: List[str], host: DataHealthHost, db=None,",
        "):",
        load("_check_data_health"),
    ],
)

print("assemble done")
